/**************************************************************************************************/

/*  ###################################################################
**     This component module is generated by Lin_Geny. Do not modify it.
**
**     @file      lin_cfg.c
**
**     @date      2025-11-15 14:43:31 PM
**
**     @brief     Lin configuration file
**
**     @version   V4_1
**
**     @Toolversion   LIN Geny V1.13
**
**     @Ldf1FileName   MVP17_20251115.ldf
**
**     @Ldf2FileName   
**
**     @Ldf3FileName   
**
**     @Ldf4FileName   
**
**     Copyright : 2024 - 2124 Ed, Inc.
**     Copyright 2024 - 2124 Ed
**     All Rights Reserved.
** ###################################################################*/

/**************************************************************************************************/
#include "Include.h"

const l_ifc_handle g_lin_hardware_ifc[HARDWARE_INSTANCE_COUNT] = {LI0};
const uint32_t g_lin_virtual_ifc[LIN_NUM_OF_IFCS] = {0};
/* definition and initialization of signal array */
volatile uint8_t    g_lin_Diag_Tx_data_Len =8;
volatile uint8_t    g_lin_Diag_Tx_data_buffer[LIN_DIAG_TX_BUF_SIZE] ={0};
volatile uint8_t    g_lin_Diag_Rx_data_buffer[LIN_DIAG_RX_BUF_SIZE] ={0};

volatile uint8_t    g_lin_Proprietary_Tx_data_buffer[LIN_PROPRIETARY_TX_BUF_SIZE] ={0};
volatile uint8_t    g_lin_Proprietary_Rx_data_buffer[LIN_PROPRIETARY_RX_BUF_SIZE] ={0};
lin_user_config_t lin1_InitConfig0 = {
    .baudRate = 19200U,
    .nodeFunction = (bool)SLAVE,
    .autobaudEnable = false,
    .classicPID = NULL,
    .numOfClassicPID = 0U,
};
volatile uint8_t    g_lin_tbl_use_index = LI0_Schedule_Index0;
/* definition and initialization of signal array */
volatile uint8_t    g_lin_frame_tbl0_data_buffer[LIN_FRAME_TBL0_BUF_SIZE] =
{
/* start of frame LI0_TBL0_MVP17_Ctrl */
   0x00 /* 0 */
  ,0x00 /* 1 */
  ,0x00 /* 2 */
  ,0x00 /* 3 */
  ,0x00 /* 4 */
  ,0x00 /* 5 */
  ,0x00 /* 6 */
  ,0x00 /* 7 */
/* start of frame LI0_TBL0_MVP17_Pressure_0_3 */
  ,0x00 /* 8 */
  ,0x00 /* 9 */
  ,0x00 /* 10 */
  ,0x00 /* 11 */
  ,0x00 /* 12 */
  ,0x00 /* 13 */
  ,0x00 /* 14 */
  ,0x00 /* 15 */
/* start of frame LI0_TBL0_MVP17_Pressure_4_7 */
  ,0x00 /* 16 */
  ,0x00 /* 17 */
  ,0x00 /* 18 */
  ,0x00 /* 19 */
  ,0x00 /* 20 */
  ,0x00 /* 21 */
  ,0x00 /* 22 */
  ,0x00 /* 23 */
/* start of frame LI0_TBL0_MVP17_Pressure_8_10 */
  ,0x00 /* 24 */
  ,0x00 /* 25 */
  ,0x00 /* 26 */
  ,0x00 /* 27 */
  ,0x00 /* 28 */
  ,0x00 /* 29 */
  ,0xff /* 30 */
  ,0xff /* 31 */
/* start of frame LI0_TBL0_Sensor_Temperature_0_7 */
  ,0x00 /* 32 */
  ,0x00 /* 33 */
  ,0x00 /* 34 */
  ,0x00 /* 35 */
  ,0x00 /* 36 */
  ,0x00 /* 37 */
  ,0x00 /* 38 */
  ,0x00 /* 39 */
/* start of frame LI0_TBL0_Memory_Pressure */
  ,0x00 /* 40 */
  ,0x00 /* 41 */
  ,0x00 /* 42 */
  ,0x00 /* 43 */
  ,0x00 /* 44 */
  ,0x00 /* 45 */
  ,0x00 /* 46 */
  ,0x00 /* 47 */
/* start of frame LI0_TBL0_MVP17_State */
  ,0x80 /* 48 */
  ,0x00 /* 49 */
  ,0x80 /* 50 */
  ,0xff /* 51 */
  ,0xff /* 52 */
  ,0xff /* 53 */
  ,0xff /* 54 */
  ,0xff /* 55 */
/* start of frame LI0_TBL0_Senor_Temperature_other */
  ,0x00 /* 56 */
  ,0x00 /* 57 */
  ,0x00 /* 58 */
  ,0x00 /* 59 */
  ,0xff /* 60 */
  ,0xff /* 61 */
  ,0xff /* 62 */
  ,0xff /* 63 */
/* start of frame LI0_TBL0_MVP17_RUN */
  ,0x00 /* 64 */
  ,0xff /* 65 */
  ,0x00 /* 66 */
  ,0x00 /* 67 */
  ,0x00 /* 68 */
  ,0x00 /* 69 */
  ,0xf0 /* 70 */
  ,0xff /* 71 */
};
/* ********************************  Frame table **********************************/
static const lin_frame_t lin_frame_tbl0[LIN_TBL0_NUM_OF_FRMS] ={

    { LIN_FRM_UNCD, 8, LIN_RES_SUB, 0}

   ,{ LIN_FRM_UNCD, 8, LIN_RES_PUB, 8}

   ,{ LIN_FRM_UNCD, 8, LIN_RES_PUB, 16}

   ,{ LIN_FRM_UNCD, 8, LIN_RES_PUB, 24}

   ,{ LIN_FRM_UNCD, 8, LIN_RES_PUB, 32}

   ,{ LIN_FRM_UNCD, 8, LIN_RES_PUB, 40}

   ,{ LIN_FRM_UNCD, 8, LIN_RES_PUB, 48}

   ,{ LIN_FRM_UNCD, 8, LIN_RES_PUB, 56}

   ,{ LIN_FRM_UNCD, 8, LIN_RES_PUB, 64}

   ,{ LIN_FRM_DIAG, 8, LIN_RES_SUB, 0}

   ,{ LIN_FRM_DIAG, 8, LIN_RES_PUB, 0  }

   ,{ LIN_FRM_PROPRIETARY, 8, LIN_RES_SUB, 0  }

   ,{ LIN_FRM_PROPRIETARY, 8, LIN_RES_PUB, 0  }

};
static uint8_t LI0_lin_Schedule_TblEnable[LIN_NUM_OF_SCHEDULE_TBL] ={TRUE};
static uint8_t LI0_lin_tbl0_NodeSendRecvEnable[LIN_TBL0_NUM_OF_FRMS] ={TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE};

static uint8_t LI0_lin_tbl0_configuration_RAM[LI0_LIN_TBL0_SIZE_OF_CFG]= {0x00, 0x11, 0x21, 0x22, 0x23, 0x24, 0x26, 0x12, 0x25, 0x27, 0x3C, 0x3D, 0x3E, 0x3F, 0xFF};

static const uint16_t  LI0_lin_tbl0_configuration_ROM[LI0_LIN_TBL0_SIZE_OF_CFG]= {0x0000, 0x11, 0x21, 0x22, 0x23, 0x24, 0x26, 0x12, 0x25, 0x27, 0x3C, 0x3D, 0x3E, 0x3F, 0xFFFF};

lin_protocol_ResponeErr_Type LI0_lin_ResponeErr_Status;
/* ************** Node attributes Initialization  ****************************/
const lin_node_attribute_t      g_lin_node_attribute_array[LIN_NUM_OF_SLAVE_IFCS]= {
    /*  LI0 **/
    {
        .product_id = {0x0000, 0x0000, 0x00},   /*{<supplier_id>,<function_id>,<variant>}*/
        .ResponeErr_Type = &LI0_lin_ResponeErr_Status,

    }
};

/* **************************LIN interface configuration ****************************/
const lin_protocol_user_config_t g_lin_protocol_user_cfg_array[LIN_NUM_OF_IFCS] = {

    /* Interface_name = LI0 */
    {
        .protocol_version = LIN_PROTOCOL_21,         /*lin_protocol_version */
        .language_version = LIN_PROTOCOL_21,         /*lin_language_version */
        .diagnostic_class = LIN_DIAGNOSTIC_CLASS_I,            /* LIN Diagnostic Class */
        .function = (bool)LIN_SLAVE,                  /*  function LIN_SLAVE*/

        .number_of_schedule_Tbl = LIN_NUM_OF_SCHEDULE_TBL,                            /*  num_of_Schedule tbl */
        .frame_start = 0,                              /*  frame_start */
        .max_idle_timeout_cnt =  5000,     /* Max Idle Timeout Count ,Max Time 5s*/
        .slave_ifc_handle = LI0_Slave,
        .lin_user_config_ptr = &lin1_InitConfig0,
        .list_schedule_tbl_En_ptr = LI0_lin_Schedule_TblEnable,        /* Schedule Tbl Enable*/

    }
};
/* **************************LIN LDF Infomation configuration ****************************/
const lin_protocol_Ldf_config_t g_lin_protocol_ldf_cfg_array[LIN_NUM_OF_SCHEDULE_TBL] = {

{
        .number_of_configurable_frames = LIN_TBL0_NUM_OF_FRMS,          /*  num_of_frames */
        .number_of_configurable_buf = LIN_FRAME_TBL0_BUF_SIZE,          /*  num_of_frames buf*/
        .list_Node_tbl_En_ptr = LI0_lin_tbl0_NodeSendRecvEnable,        /* frame SendRecv Enable*/
        .frame_tbl_ptr = lin_frame_tbl0,                                 /*  frame_tbl */
        .list_identifiers_ROM_ptr = LI0_lin_tbl0_configuration_ROM,                  /*  *configuration_ROM */

        .list_identifiers_RAM_ptr = LI0_lin_tbl0_configuration_RAM,                            /*  *configuration_RAM */
        .Frame_Buff_data_ptr = g_lin_frame_tbl0_data_buffer,                              /*  *frame cfg buff ptr*/

    },
};
void ld_Set_lin_schedule_tbl_use_En(uint8_t OpScheduleTblIndex,uint8_t data)
{
    if(OpScheduleTblIndex<(g_lin_protocol_user_cfg_array[LI0].number_of_schedule_Tbl))
    {
        g_lin_protocol_user_cfg_array[LI0].list_schedule_tbl_En_ptr[OpScheduleTblIndex] = data;
    }

}

lin_protocol_ResponeErr_Type* ld_Get_lin_ResponeErr_Status(void)
{
    return &LI0_lin_ResponeErr_Status; 
}
void ld_Set_id_Respone_En(uint8_t OpScheduleTblIndex,uint8_t OpFrameIndex,uint8_t data)
{
    if(OpFrameIndex<(g_lin_protocol_ldf_cfg_array[OpScheduleTblIndex].number_of_configurable_frames))
    {
        g_lin_protocol_ldf_cfg_array[OpScheduleTblIndex].list_Node_tbl_En_ptr[OpFrameIndex] = data;
    }

}
