/**************************************************************************************************/

/*  ###################################################################
**     This component module is generated by Lin_Geny. Do not modify it.
**
**     @file      lin_cfg.h
**
**     @date      2025-11-15 14:43:31 PM
**
**     @brief     Lin configuration file
**
**     @version   V4_1
**
**     @Toolversion   LIN Geny V1.13
**
**     @Ldf1FileName   MVP17_20251115.ldf
**
**     @Ldf2FileName   
**
**     @Ldf3FileName   
**
**     @Ldf4FileName   
**
**     Copyright : 2024 - 2124 Ed, Inc.
**     Copyright 2024 - 2124 Ed
**     All Rights Reserved.
** ###################################################################*/

/**************************************************************************************************/
#ifndef    LIN_CFG_H
#define    LIN_CFG_H


/* Implements    : SUPPORT_MASTER_MODE_Class */
#define SUPPORT_MASTER_MODE     0U /* Equal to 1 when have at least one master interface */
/* Implements    : SUPPORT_SLAVE_MODE_Class */
#define SUPPORT_SLAVE_MODE      1U  /* Equal to 1 when have at least one slave interface */

/* Implements    : SUPPORT_PROTOCOL_21_Class */
#define SUPPORT_PROTOCOL_21     1U /* Equal to 1 when have at least one LIN2.1 or LIN2.2 interface */
/* Implements    : SUPPORT_PROTOCOL_J2602_Class */
#define SUPPORT_PROTOCOL_J2602  0U /* Equal to 1 when have at least one J2602 interface */
/* Implements    : SUPPORT_DIAG_CLASS_III_Class */
#define SUPPORT_DIAG_CLASS_III  0U /* Equal to 1 when have at least one ifc with diagnostic class III */
/* Implements    : SUPPORT_DIAG_CLASS_II_Class */
#define SUPPORT_DIAG_CLASS_II   0U /* Equal to 1 when have at least one ifc with diagnostic class II or III */
/* Implements    : SUPPORT_TRANSPORT_LAYER_Class */
#define SUPPORT_TRANSPORT_LAYER 0U /* Equal to 1 to use transport layer */
/* Implements    : SUPPORT_DIAG_SERVICE_Class */
#define SUPPORT_DIAG_SERVICE    1U /* Equal to 1 to use diagnostic service layer */
#define TIME_OUT_UNIT_US 534U

#define HARDWARE_INSTANCE_COUNT    1U
#define LIN_NUM_OF_IFCS  1U
#define LIN_NUM_OF_SLAVE_IFCS 1U
#define LIN_NUM_OF_MASTER_IFCS 0U

#define LIN_DIAG_TX_BUF_SIZE          8U
#define LIN_DIAG_RX_BUF_SIZE          8U

#define LIN_PROPRIETARY_TX_BUF_SIZE          8U
#define LIN_PROPRIETARY_RX_BUF_SIZE          8U
/* ********************************************************************/
/* *************               Interfaces           *******************/
/* ********************************************************************/
typedef enum {
   LI0 = 0x00U,
   INVALID_IFC = 0xFFU
}l_ifc_handle;

typedef enum {
   LI0_Slave = 0x00U,
   INVALID_SLAVE_INDEX = 0xFFU
}l_ifc_slave_handle;
typedef enum {
   INVALID_MASTER_INDEX = 0xFFU
}l_ifc_master_handle;

/* Number of Ldf schedule */
#define LIN_NUM_OF_SCHEDULE_TBL  1U

typedef enum {
    LI0_Schedule_Index0 = 0U
}l_ifc_Schedule_Index;
/* ********************************************************************/
/* *************               Signals              *******************/
/* ********************************************************************/
/* Number of signals */
#define LI0_LIN_TBL0_NUM_OF_SIGS  64U
/* List of signals */
typedef enum {
   /* All signals for LIN Schedule Table0 node */
    
       /* Interface_name = LI0 */
       
     LI0_TBL0_MVP17_Req_MassageGrade
   , LI0_TBL0_MVP17_Req_MassageMode
   , LI0_TBL0_MVP17_Req_MassageEnable
   , LI0_TBL0_MVP17_Req_Lumbar
   , LI0_TBL0_MVP17_Req_Adaptive_Lumbar_Switch
   , LI0_TBL0_MVP17_Req_Lumbar_Memory
   , LI0_TBL0_MVP17_Req_Flank
   , LI0_TBL0_MVP17_Req_Flank_Memory
   , LI0_TBL0_MVP17_Req_Active_Flank_Switch
   , LI0_TBL0_MVP17_Req_Active_Flank_Ctrl
   , LI0_TBL0_MVP17_Req_Active_Flank_Sensitivity
   , LI0_TBL0_MVP17_Req_Adaptive_Flank_Switch
   , LI0_TBL0_MVP17_Req_PressEn
   , LI0_TBL0_MVP17_Pressure0
   , LI0_TBL0_MVP17_Pressure1
   , LI0_TBL0_MVP17_Pressure2
   , LI0_TBL0_MVP17_Pressure3
   , LI0_TBL0_MVP17_Pressure4
   , LI0_TBL0_MVP17_Pressure5
   , LI0_TBL0_MVP17_Pressure6
   , LI0_TBL0_MVP17_Pressure7
   , LI0_TBL0_MVP17_Pressure8
   , LI0_TBL0_MVP17_Pressure9
   , LI0_TBL0_MVP17_Pressure10
   , LI0_TBL0_Sensor_Temperature0
   , LI0_TBL0_Sensor_Temperature1
   , LI0_TBL0_Sensor_Temperature2
   , LI0_TBL0_Sensor_Temperature3
   , LI0_TBL0_Sensor_Temperature4
   , LI0_TBL0_Sensor_Temperature5
   , LI0_TBL0_Sensor_Temperature6
   , LI0_TBL0_Sensor_Temperature7
   , LI0_TBL0_MVP17_State_LumbarMemory_lowBladderPressure
   , LI0_TBL0_MVP17_State_LumbarMemory_UpBladderPressure
   , LI0_TBL0_MVP17_State_FlankMemory_LeftPressure
   , LI0_TBL0_MVP17_State_FlankMemory_RigntPressure
   , LI0_TBL0_FK_MassageMode
   , LI0_TBL0_FK_MassageGrade
   , LI0_TBL0_MVP17_State_MassageSwitch
   , LI0_TBL0_MVP17_ValveFaultState
   , LI0_TBL0_MVP17_PumpFaultState
   , LI0_TBL0_MVP17_Response_Error
   , LI0_TBL0_MVP17_BattVolFaultState
   , LI0_TBL0_Sensor_Temperature8
   , LI0_TBL0_Sensor_Temperature9
   , LI0_TBL0_Sensor_Temperature10
   , LI0_TBL0_Ntc_Temperature
   , LI0_TBL0_Massage_Dot1
   , LI0_TBL0_Massage_Dot2
   , LI0_TBL0_Massage_Dot3
   , LI0_TBL0_Massage_Dot4
   , LI0_TBL0_Massage_Dot5
   , LI0_TBL0_Massage_Dot6
   , LI0_TBL0_Massage_Dot7
   , LI0_TBL0_Massage_Dot8
   , LI0_TBL0_Flank_Right
   , LI0_TBL0_Flank_Left
   , LI0_TBL0_Lumbar_UP
   , LI0_TBL0_Lumbar_Down
   , LI0_TBL0_Sensor_Bag1
   , LI0_TBL0_Sensor_Bag2
   , LI0_TBL0_Sensor_Bag3
   , LI0_TBL0_Sensor_Bag4
   , LI0_TBL0_GasStorage

} l_signal_handle_Tbl0;
/**********************************************************************/
/*****************               Frame             ********************/
/**********************************************************************/
/* Number of frames */
#define LIN_TBL0_NUM_OF_FRMS  13U
#define LI0_LIN_TBL0_SIZE_OF_CFG  17U
/* frame buffer size */
#define LIN_FRAME_TBL0_BUF_SIZE          72U
/* List of frames */
typedef enum {
   /* All frames for LIN Schedule Table0 node */
    
   /* Interface_name = LI0 */

     LI0_TBL0_MVP17_Ctrl
   , LI0_TBL0_MVP17_Pressure_0_3
   , LI0_TBL0_MVP17_Pressure_4_7
   , LI0_TBL0_MVP17_Pressure_8_10
   , LI0_TBL0_Sensor_Temperature_0_7
   , LI0_TBL0_Memory_Pressure
   , LI0_TBL0_MVP17_State
   , LI0_TBL0_Senor_Temperature_other
   , LI0_TBL0_MVP17_RUN
   , LI0_TBL0_DiagMasterReq
   , LI0_TBL0_DiagSlaveResp
   , LI0_TBL0_PrietaryMasterReq
   , LI0_TBL0_PrietarySlaveResp

} l_frame_handle_Tbl0;
/* ********************************************************************/
/* *************             Configuration          *******************/
/* ********************************************************************/


/* Size of configuration in ROM and RAM used for interface: LI0 */

/* *******************************************************************
 * global macros
 *********************************************************************/
/*FUNCTION**********************************************************************
 *
 * Function Name : BOOL_rd
 * Description   : This function return value of bool signal
 *
 * Implements    : BOOL_rd_Class
 *END**************************************************************************/
#define BOOL_rd(SIGNAL) BOOL_rd_##SIGNAL()

/*FUNCTION**********************************************************************
 *
 * Function Name : BOOL_wr
 * Description   : This function write value A to bool signal
 *
 * Implements    : BOOL_wr_Class
 *END**************************************************************************/
#define BOOL_wr(SIGNAL, A) BOOL_wr_##SIGNAL(A)

/*FUNCTION**********************************************************************
 *
 * Function Name : uint8_t_rd
 * Description   : This function read data from (1-8 bit)signal
 *
 * Implements    : uint8_t_rd_Class
 *END**************************************************************************/
#define uint8_t_rd(SIGNAL) uint8_t_rd_##SIGNAL()

/*FUNCTION**********************************************************************
 *
 * Function Name : uint8_t_wr
 * Description   : This this function write data to (1-8 bit)signal
 *
 * Implements    : uint8_t_wr_Class
 *END**************************************************************************/
#define uint8_t_wr(SIGNAL, A) uint8_t_wr_##SIGNAL(A)

/*FUNCTION**********************************************************************
 *
 * Function Name : uint16_t_rd
 * Description   : This function read data from (8-16 bit)signal
 *
 * Implements    : uint16_t_rd_Class
 *END**************************************************************************/
#define uint16_t_rd(SIGNAL) uint16_t_rd_##SIGNAL()

/*FUNCTION**********************************************************************
 *
 * Function Name : uint16_t_wr
 * Description   : This function write data to (8-16 bit) signal
 *
 * Implements    : uint16_t_wr_Class
 *END**************************************************************************/
#define uint16_t_wr(SIGNAL, A) uint16_t_wr_##SIGNAL(A)

/*FUNCTION**********************************************************************
 *
 * Function Name : l_bytes_rd
 * Description   : This function read data from bytes signal
 *
 * Implements    : l_bytes_rd_Class
 *END**************************************************************************/
#define l_bytes_rd(SIGNAL, start, count, data)  l_bytes_rd_##SIGNAL(start, count, data)

/*FUNCTION**********************************************************************
 *
 * Function Name : l_bytes_wr
 * Description   : This function write data to bytes signal
 *
 * Implements    : l_bytes_wr_Class
 *END**************************************************************************/
#define l_bytes_wr(SIGNAL, start, count, data) l_bytes_wr_##SIGNAL(start, count, data)

/*FUNCTION**********************************************************************
 *
 * Function Name : l_flg_tst
 * Description   : This function return value of flag which related with signal
 *
 * Implements    : l_flg_tst_Class
 *END**************************************************************************/
#define l_flg_tst(FLAG) l_flg_tst_##FLAG()

/*FUNCTION**********************************************************************
 *
 * Function Name : l_flg_clr
 * Description   : This function clear flag which related with signal
 *
 * Implements    : l_flg_clr_Class
 *END**************************************************************************/
#define l_flg_clr(FLAG) l_flg_clr_##FLAG()

#define LIN_TEST_BIT(A,B) ((BOOL)((((A) & (1U << (B))) != 0U) ? 1U : 0U))
#define LIN_SET_BIT(A,B)                      ((A) |= (uint8_t) (1U << (B)))
#define LIN_CLEAR_BIT(A,B)               ((A) &= ((uint8_t) (~(1U << (B)))))
#define LIN_BYTE_MASK  ((uint16_t)(((uint16_t)((uint16_t)1 << CHAR_BIT)) - (uint16_t)1))


/* Returns the low byte of the 32-bit value    */
#define BYTE_0(n)                              ((uint8_t)((n) & (uint8_t)0xFF))
/* Returns the second byte of the 32-bit value */
#define BYTE_1(n)                        ((uint8_t)(BYTE_0((n) >> (uint8_t)8)))
/* Returns the third byte of the 32-bit value  */
#define BYTE_2(n)                       ((uint8_t)(BYTE_0((n) >> (uint8_t)16)))
/* Returns high byte of the 32-bit value       */
#define BYTE_3(n)                       ((uint8_t)(BYTE_0((n) >> (uint8_t)24)))

/*
 * defines for signal access
 */

/* Schedule table 0 signal access*/
#define LIN_LI0_TBL0_MVP17_Req_MassageGrade_BYTE_OFFSET    0U
#define LIN_LI0_TBL0_MVP17_Req_MassageGrade_BIT_OFFSET    0U
#define LIN_LI0_TBL0_MVP17_Req_MassageGrade_SIGNAL_SIZE    2U


#define LIN_LI0_TBL0_MVP17_Req_MassageMode_BYTE_OFFSET    0U
#define LIN_LI0_TBL0_MVP17_Req_MassageMode_BIT_OFFSET    2U
#define LIN_LI0_TBL0_MVP17_Req_MassageMode_SIGNAL_SIZE    3U


#define LIN_LI0_TBL0_MVP17_Req_MassageEnable_BYTE_OFFSET    0U
#define LIN_LI0_TBL0_MVP17_Req_MassageEnable_BIT_OFFSET    5U
#define LIN_LI0_TBL0_MVP17_Req_MassageEnable_SIGNAL_SIZE    2U


#define LIN_LI0_TBL0_MVP17_Req_Lumbar_BYTE_OFFSET    1U
#define LIN_LI0_TBL0_MVP17_Req_Lumbar_BIT_OFFSET    0U
#define LIN_LI0_TBL0_MVP17_Req_Lumbar_SIGNAL_SIZE    3U


#define LIN_LI0_TBL0_MVP17_Req_Adaptive_Lumbar_Switch_BYTE_OFFSET    1U
#define LIN_LI0_TBL0_MVP17_Req_Adaptive_Lumbar_Switch_BIT_OFFSET    3U
#define LIN_LI0_TBL0_MVP17_Req_Adaptive_Lumbar_Switch_SIGNAL_SIZE    2U


#define LIN_LI0_TBL0_MVP17_Req_Lumbar_Memory_BYTE_OFFSET    1U
#define LIN_LI0_TBL0_MVP17_Req_Lumbar_Memory_BIT_OFFSET    5U
#define LIN_LI0_TBL0_MVP17_Req_Lumbar_Memory_SIGNAL_SIZE    2U


#define LIN_LI0_TBL0_MVP17_Req_Flank_BYTE_OFFSET    2U
#define LIN_LI0_TBL0_MVP17_Req_Flank_BIT_OFFSET    0U
#define LIN_LI0_TBL0_MVP17_Req_Flank_SIGNAL_SIZE    3U


#define LIN_LI0_TBL0_MVP17_Req_Flank_Memory_BYTE_OFFSET    2U
#define LIN_LI0_TBL0_MVP17_Req_Flank_Memory_BIT_OFFSET    3U
#define LIN_LI0_TBL0_MVP17_Req_Flank_Memory_SIGNAL_SIZE    2U


#define LIN_LI0_TBL0_MVP17_Req_Active_Flank_Switch_BYTE_OFFSET    2U
#define LIN_LI0_TBL0_MVP17_Req_Active_Flank_Switch_BIT_OFFSET    5U
#define LIN_LI0_TBL0_MVP17_Req_Active_Flank_Switch_SIGNAL_SIZE    2U


#define LIN_LI0_TBL0_MVP17_Req_Active_Flank_Ctrl_BYTE_OFFSET    3U
#define LIN_LI0_TBL0_MVP17_Req_Active_Flank_Ctrl_BIT_OFFSET    0U
#define LIN_LI0_TBL0_MVP17_Req_Active_Flank_Ctrl_SIGNAL_SIZE    3U


#define LIN_LI0_TBL0_MVP17_Req_Active_Flank_Sensitivity_BYTE_OFFSET    3U
#define LIN_LI0_TBL0_MVP17_Req_Active_Flank_Sensitivity_BIT_OFFSET    3U
#define LIN_LI0_TBL0_MVP17_Req_Active_Flank_Sensitivity_SIGNAL_SIZE    2U


#define LIN_LI0_TBL0_MVP17_Req_Adaptive_Flank_Switch_BYTE_OFFSET    3U
#define LIN_LI0_TBL0_MVP17_Req_Adaptive_Flank_Switch_BIT_OFFSET    5U
#define LIN_LI0_TBL0_MVP17_Req_Adaptive_Flank_Switch_SIGNAL_SIZE    2U


#define LIN_LI0_TBL0_MVP17_Req_PressEn_BYTE_OFFSET    3U
#define LIN_LI0_TBL0_MVP17_Req_PressEn_BIT_OFFSET    7U
#define LIN_LI0_TBL0_MVP17_Req_PressEn_SIGNAL_SIZE    1U


#define LIN_LI0_TBL0_MVP17_Pressure0_BYTE_OFFSET    8U
#define LIN_LI0_TBL0_MVP17_Pressure0_BIT_OFFSET    0U
#define LIN_LI0_TBL0_MVP17_Pressure0_SIGNAL_SIZE    16U

#define LIN_LI0_TBL0_MVP17_Pressure1_BYTE_OFFSET    10U
#define LIN_LI0_TBL0_MVP17_Pressure1_BIT_OFFSET    0U
#define LIN_LI0_TBL0_MVP17_Pressure1_SIGNAL_SIZE    16U

#define LIN_LI0_TBL0_MVP17_Pressure2_BYTE_OFFSET    12U
#define LIN_LI0_TBL0_MVP17_Pressure2_BIT_OFFSET    0U
#define LIN_LI0_TBL0_MVP17_Pressure2_SIGNAL_SIZE    16U

#define LIN_LI0_TBL0_MVP17_Pressure3_BYTE_OFFSET    14U
#define LIN_LI0_TBL0_MVP17_Pressure3_BIT_OFFSET    0U
#define LIN_LI0_TBL0_MVP17_Pressure3_SIGNAL_SIZE    16U

#define LIN_LI0_TBL0_MVP17_Pressure4_BYTE_OFFSET    16U
#define LIN_LI0_TBL0_MVP17_Pressure4_BIT_OFFSET    0U
#define LIN_LI0_TBL0_MVP17_Pressure4_SIGNAL_SIZE    16U

#define LIN_LI0_TBL0_MVP17_Pressure5_BYTE_OFFSET    18U
#define LIN_LI0_TBL0_MVP17_Pressure5_BIT_OFFSET    0U
#define LIN_LI0_TBL0_MVP17_Pressure5_SIGNAL_SIZE    16U

#define LIN_LI0_TBL0_MVP17_Pressure6_BYTE_OFFSET    20U
#define LIN_LI0_TBL0_MVP17_Pressure6_BIT_OFFSET    0U
#define LIN_LI0_TBL0_MVP17_Pressure6_SIGNAL_SIZE    16U

#define LIN_LI0_TBL0_MVP17_Pressure7_BYTE_OFFSET    22U
#define LIN_LI0_TBL0_MVP17_Pressure7_BIT_OFFSET    0U
#define LIN_LI0_TBL0_MVP17_Pressure7_SIGNAL_SIZE    16U

#define LIN_LI0_TBL0_MVP17_Pressure8_BYTE_OFFSET    24U
#define LIN_LI0_TBL0_MVP17_Pressure8_BIT_OFFSET    0U
#define LIN_LI0_TBL0_MVP17_Pressure8_SIGNAL_SIZE    16U

#define LIN_LI0_TBL0_MVP17_Pressure9_BYTE_OFFSET    26U
#define LIN_LI0_TBL0_MVP17_Pressure9_BIT_OFFSET    0U
#define LIN_LI0_TBL0_MVP17_Pressure9_SIGNAL_SIZE    16U

#define LIN_LI0_TBL0_MVP17_Pressure10_BYTE_OFFSET    28U
#define LIN_LI0_TBL0_MVP17_Pressure10_BIT_OFFSET    0U
#define LIN_LI0_TBL0_MVP17_Pressure10_SIGNAL_SIZE    16U

#define LIN_LI0_TBL0_Sensor_Temperature0_BYTE_OFFSET    32U
#define LIN_LI0_TBL0_Sensor_Temperature0_BIT_OFFSET    0U
#define LIN_LI0_TBL0_Sensor_Temperature0_SIGNAL_SIZE    8U

#define LIN_LI0_TBL0_Sensor_Temperature1_BYTE_OFFSET    33U
#define LIN_LI0_TBL0_Sensor_Temperature1_BIT_OFFSET    0U
#define LIN_LI0_TBL0_Sensor_Temperature1_SIGNAL_SIZE    8U

#define LIN_LI0_TBL0_Sensor_Temperature2_BYTE_OFFSET    34U
#define LIN_LI0_TBL0_Sensor_Temperature2_BIT_OFFSET    0U
#define LIN_LI0_TBL0_Sensor_Temperature2_SIGNAL_SIZE    8U

#define LIN_LI0_TBL0_Sensor_Temperature3_BYTE_OFFSET    35U
#define LIN_LI0_TBL0_Sensor_Temperature3_BIT_OFFSET    0U
#define LIN_LI0_TBL0_Sensor_Temperature3_SIGNAL_SIZE    8U

#define LIN_LI0_TBL0_Sensor_Temperature4_BYTE_OFFSET    36U
#define LIN_LI0_TBL0_Sensor_Temperature4_BIT_OFFSET    0U
#define LIN_LI0_TBL0_Sensor_Temperature4_SIGNAL_SIZE    8U

#define LIN_LI0_TBL0_Sensor_Temperature5_BYTE_OFFSET    37U
#define LIN_LI0_TBL0_Sensor_Temperature5_BIT_OFFSET    0U
#define LIN_LI0_TBL0_Sensor_Temperature5_SIGNAL_SIZE    8U

#define LIN_LI0_TBL0_Sensor_Temperature6_BYTE_OFFSET    38U
#define LIN_LI0_TBL0_Sensor_Temperature6_BIT_OFFSET    0U
#define LIN_LI0_TBL0_Sensor_Temperature6_SIGNAL_SIZE    8U

#define LIN_LI0_TBL0_Sensor_Temperature7_BYTE_OFFSET    39U
#define LIN_LI0_TBL0_Sensor_Temperature7_BIT_OFFSET    0U
#define LIN_LI0_TBL0_Sensor_Temperature7_SIGNAL_SIZE    8U

#define LIN_LI0_TBL0_MVP17_State_LumbarMemory_lowBladderPressure_BYTE_OFFSET    40U
#define LIN_LI0_TBL0_MVP17_State_LumbarMemory_lowBladderPressure_BIT_OFFSET    0U
#define LIN_LI0_TBL0_MVP17_State_LumbarMemory_lowBladderPressure_SIGNAL_SIZE    16U

#define LIN_LI0_TBL0_MVP17_State_LumbarMemory_UpBladderPressure_BYTE_OFFSET    42U
#define LIN_LI0_TBL0_MVP17_State_LumbarMemory_UpBladderPressure_BIT_OFFSET    0U
#define LIN_LI0_TBL0_MVP17_State_LumbarMemory_UpBladderPressure_SIGNAL_SIZE    16U

#define LIN_LI0_TBL0_MVP17_State_FlankMemory_LeftPressure_BYTE_OFFSET    44U
#define LIN_LI0_TBL0_MVP17_State_FlankMemory_LeftPressure_BIT_OFFSET    0U
#define LIN_LI0_TBL0_MVP17_State_FlankMemory_LeftPressure_SIGNAL_SIZE    16U

#define LIN_LI0_TBL0_MVP17_State_FlankMemory_RigntPressure_BYTE_OFFSET    46U
#define LIN_LI0_TBL0_MVP17_State_FlankMemory_RigntPressure_BIT_OFFSET    0U
#define LIN_LI0_TBL0_MVP17_State_FlankMemory_RigntPressure_SIGNAL_SIZE    16U

#define LIN_LI0_TBL0_FK_MassageMode_BYTE_OFFSET    48U
#define LIN_LI0_TBL0_FK_MassageMode_BIT_OFFSET    0U
#define LIN_LI0_TBL0_FK_MassageMode_SIGNAL_SIZE    3U

#define LIN_LI0_TBL0_FK_MassageGrade_BYTE_OFFSET    48U
#define LIN_LI0_TBL0_FK_MassageGrade_BIT_OFFSET    3U
#define LIN_LI0_TBL0_FK_MassageGrade_SIGNAL_SIZE    2U

#define LIN_LI0_TBL0_MVP17_State_MassageSwitch_BYTE_OFFSET    48U
#define LIN_LI0_TBL0_MVP17_State_MassageSwitch_BIT_OFFSET    5U
#define LIN_LI0_TBL0_MVP17_State_MassageSwitch_SIGNAL_SIZE    2U

#define LIN_LI0_TBL0_MVP17_ValveFaultState_BYTE_OFFSET    49U
#define LIN_LI0_TBL0_MVP17_ValveFaultState_BIT_OFFSET    0U
#define LIN_LI0_TBL0_MVP17_ValveFaultState_SIGNAL_SIZE    3U

#define LIN_LI0_TBL0_MVP17_PumpFaultState_BYTE_OFFSET    49U
#define LIN_LI0_TBL0_MVP17_PumpFaultState_BIT_OFFSET    3U
#define LIN_LI0_TBL0_MVP17_PumpFaultState_SIGNAL_SIZE    3U

#define LIN_LI0_TBL0_MVP17_Response_Error_BYTE_OFFSET    49U
#define LIN_LI0_TBL0_MVP17_Response_Error_BIT_OFFSET    6U
#define LIN_LI0_TBL0_MVP17_Response_Error_SIGNAL_SIZE    1U

#define LIN_LI0_TBL0_MVP17_BattVolFaultState_BYTE_OFFSET    49U
#define LIN_LI0_TBL0_MVP17_BattVolFaultState_BIT_OFFSET    7U
#define LIN_LI0_TBL0_MVP17_BattVolFaultState_SIGNAL_SIZE    8U

#define LIN_LI0_TBL0_Sensor_Temperature8_BYTE_OFFSET    56U
#define LIN_LI0_TBL0_Sensor_Temperature8_BIT_OFFSET    0U
#define LIN_LI0_TBL0_Sensor_Temperature8_SIGNAL_SIZE    8U

#define LIN_LI0_TBL0_Sensor_Temperature9_BYTE_OFFSET    57U
#define LIN_LI0_TBL0_Sensor_Temperature9_BIT_OFFSET    0U
#define LIN_LI0_TBL0_Sensor_Temperature9_SIGNAL_SIZE    8U

#define LIN_LI0_TBL0_Sensor_Temperature10_BYTE_OFFSET    58U
#define LIN_LI0_TBL0_Sensor_Temperature10_BIT_OFFSET    0U
#define LIN_LI0_TBL0_Sensor_Temperature10_SIGNAL_SIZE    8U

#define LIN_LI0_TBL0_Ntc_Temperature_BYTE_OFFSET    59U
#define LIN_LI0_TBL0_Ntc_Temperature_BIT_OFFSET    0U
#define LIN_LI0_TBL0_Ntc_Temperature_SIGNAL_SIZE    8U

#define LIN_LI0_TBL0_Massage_Dot1_BYTE_OFFSET    64U
#define LIN_LI0_TBL0_Massage_Dot1_BIT_OFFSET    0U
#define LIN_LI0_TBL0_Massage_Dot1_SIGNAL_SIZE    1U

#define LIN_LI0_TBL0_Massage_Dot2_BYTE_OFFSET    64U
#define LIN_LI0_TBL0_Massage_Dot2_BIT_OFFSET    1U
#define LIN_LI0_TBL0_Massage_Dot2_SIGNAL_SIZE    1U

#define LIN_LI0_TBL0_Massage_Dot3_BYTE_OFFSET    64U
#define LIN_LI0_TBL0_Massage_Dot3_BIT_OFFSET    2U
#define LIN_LI0_TBL0_Massage_Dot3_SIGNAL_SIZE    1U

#define LIN_LI0_TBL0_Massage_Dot4_BYTE_OFFSET    64U
#define LIN_LI0_TBL0_Massage_Dot4_BIT_OFFSET    3U
#define LIN_LI0_TBL0_Massage_Dot4_SIGNAL_SIZE    1U

#define LIN_LI0_TBL0_Massage_Dot5_BYTE_OFFSET    64U
#define LIN_LI0_TBL0_Massage_Dot5_BIT_OFFSET    4U
#define LIN_LI0_TBL0_Massage_Dot5_SIGNAL_SIZE    1U

#define LIN_LI0_TBL0_Massage_Dot6_BYTE_OFFSET    64U
#define LIN_LI0_TBL0_Massage_Dot6_BIT_OFFSET    5U
#define LIN_LI0_TBL0_Massage_Dot6_SIGNAL_SIZE    1U

#define LIN_LI0_TBL0_Massage_Dot7_BYTE_OFFSET    64U
#define LIN_LI0_TBL0_Massage_Dot7_BIT_OFFSET    6U
#define LIN_LI0_TBL0_Massage_Dot7_SIGNAL_SIZE    1U

#define LIN_LI0_TBL0_Massage_Dot8_BYTE_OFFSET    64U
#define LIN_LI0_TBL0_Massage_Dot8_BIT_OFFSET    7U
#define LIN_LI0_TBL0_Massage_Dot8_SIGNAL_SIZE    1U

#define LIN_LI0_TBL0_Flank_Right_BYTE_OFFSET    66U
#define LIN_LI0_TBL0_Flank_Right_BIT_OFFSET    0U
#define LIN_LI0_TBL0_Flank_Right_SIGNAL_SIZE    4U

#define LIN_LI0_TBL0_Flank_Left_BYTE_OFFSET    66U
#define LIN_LI0_TBL0_Flank_Left_BIT_OFFSET    4U
#define LIN_LI0_TBL0_Flank_Left_SIGNAL_SIZE    4U

#define LIN_LI0_TBL0_Lumbar_UP_BYTE_OFFSET    67U
#define LIN_LI0_TBL0_Lumbar_UP_BIT_OFFSET    0U
#define LIN_LI0_TBL0_Lumbar_UP_SIGNAL_SIZE    4U

#define LIN_LI0_TBL0_Lumbar_Down_BYTE_OFFSET    67U
#define LIN_LI0_TBL0_Lumbar_Down_BIT_OFFSET    4U
#define LIN_LI0_TBL0_Lumbar_Down_SIGNAL_SIZE    4U

#define LIN_LI0_TBL0_Sensor_Bag1_BYTE_OFFSET    68U
#define LIN_LI0_TBL0_Sensor_Bag1_BIT_OFFSET    0U
#define LIN_LI0_TBL0_Sensor_Bag1_SIGNAL_SIZE    4U

#define LIN_LI0_TBL0_Sensor_Bag2_BYTE_OFFSET    68U
#define LIN_LI0_TBL0_Sensor_Bag2_BIT_OFFSET    4U
#define LIN_LI0_TBL0_Sensor_Bag2_SIGNAL_SIZE    4U

#define LIN_LI0_TBL0_Sensor_Bag3_BYTE_OFFSET    69U
#define LIN_LI0_TBL0_Sensor_Bag3_BIT_OFFSET    0U
#define LIN_LI0_TBL0_Sensor_Bag3_SIGNAL_SIZE    4U

#define LIN_LI0_TBL0_Sensor_Bag4_BYTE_OFFSET    69U
#define LIN_LI0_TBL0_Sensor_Bag4_BIT_OFFSET    4U
#define LIN_LI0_TBL0_Sensor_Bag4_SIGNAL_SIZE    4U

#define LIN_LI0_TBL0_GasStorage_BYTE_OFFSET    70U
#define LIN_LI0_TBL0_GasStorage_BIT_OFFSET    0U
#define LIN_LI0_TBL0_GasStorage_SIGNAL_SIZE    4U

/* ********************************************************************/
/* *************        Static API Functions        *******************/
/* ********************************************************************/
/*
 * the static signal access macros
 */


/* static access macros for signal LI0_TBL0_MVP17_Req_MassageGrade */


#define uint8_t_rd_LI0_TBL0_MVP17_Req_MassageGrade() \
    ((uint8_t)  (((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Req_MassageGrade_BYTE_OFFSET]) >> 0U) & 0x03U))


#define uint8_t_wr_LI0_TBL0_MVP17_Req_MassageGrade(A) \
    { \
    g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Req_MassageGrade_BYTE_OFFSET] = \
    (uint8_t)((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Req_MassageGrade_BYTE_OFFSET] & 0xfcU) | \
    (((A) << 0U) & 0x03U)); \
    }
/* static access macros for signal LI0_TBL0_MVP17_Req_MassageMode */


#define uint8_t_rd_LI0_TBL0_MVP17_Req_MassageMode() \
    ((uint8_t)  (((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Req_MassageMode_BYTE_OFFSET]) >> 2U) & 0x07U))


#define uint8_t_wr_LI0_TBL0_MVP17_Req_MassageMode(A) \
    { \
    g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Req_MassageMode_BYTE_OFFSET] = \
    (uint8_t)((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Req_MassageMode_BYTE_OFFSET] & 0xe3U) | \
    (((A) << 2U) & 0x1cU)); \
    }
/* static access macros for signal LI0_TBL0_MVP17_Req_MassageEnable */


#define uint8_t_rd_LI0_TBL0_MVP17_Req_MassageEnable() \
    ((uint8_t)  (((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Req_MassageEnable_BYTE_OFFSET]) >> 5U) & 0x03U))


#define uint8_t_wr_LI0_TBL0_MVP17_Req_MassageEnable(A) \
    { \
    g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Req_MassageEnable_BYTE_OFFSET] = \
    (uint8_t)((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Req_MassageEnable_BYTE_OFFSET] & 0x9fU) | \
    (((A) << 5U) & 0x60U)); \
    }
/* static access macros for signal LI0_TBL0_MVP17_Req_Lumbar */


#define uint8_t_rd_LI0_TBL0_MVP17_Req_Lumbar() \
    ((uint8_t)  (((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Req_Lumbar_BYTE_OFFSET]) >> 0U) & 0x07U))


#define uint8_t_wr_LI0_TBL0_MVP17_Req_Lumbar(A) \
    { \
    g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Req_Lumbar_BYTE_OFFSET] = \
    (uint8_t)((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Req_Lumbar_BYTE_OFFSET] & 0xf8U) | \
    (((A) << 0U) & 0x07U)); \
    }
/* static access macros for signal LI0_TBL0_MVP17_Req_Adaptive_Lumbar_Switch */


#define uint8_t_rd_LI0_TBL0_MVP17_Req_Adaptive_Lumbar_Switch() \
    ((uint8_t)  (((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Req_Adaptive_Lumbar_Switch_BYTE_OFFSET]) >> 3U) & 0x03U))


#define uint8_t_wr_LI0_TBL0_MVP17_Req_Adaptive_Lumbar_Switch(A) \
    { \
    g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Req_Adaptive_Lumbar_Switch_BYTE_OFFSET] = \
    (uint8_t)((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Req_Adaptive_Lumbar_Switch_BYTE_OFFSET] & 0xe7U) | \
    (((A) << 3U) & 0x18U)); \
    }
/* static access macros for signal LI0_TBL0_MVP17_Req_Lumbar_Memory */


#define uint8_t_rd_LI0_TBL0_MVP17_Req_Lumbar_Memory() \
    ((uint8_t)  (((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Req_Lumbar_Memory_BYTE_OFFSET]) >> 5U) & 0x03U))


#define uint8_t_wr_LI0_TBL0_MVP17_Req_Lumbar_Memory(A) \
    { \
    g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Req_Lumbar_Memory_BYTE_OFFSET] = \
    (uint8_t)((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Req_Lumbar_Memory_BYTE_OFFSET] & 0x9fU) | \
    (((A) << 5U) & 0x60U)); \
    }
/* static access macros for signal LI0_TBL0_MVP17_Req_Flank */


#define uint8_t_rd_LI0_TBL0_MVP17_Req_Flank() \
    ((uint8_t)  (((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Req_Flank_BYTE_OFFSET]) >> 0U) & 0x07U))


#define uint8_t_wr_LI0_TBL0_MVP17_Req_Flank(A) \
    { \
    g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Req_Flank_BYTE_OFFSET] = \
    (uint8_t)((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Req_Flank_BYTE_OFFSET] & 0xf8U) | \
    (((A) << 0U) & 0x07U)); \
    }
/* static access macros for signal LI0_TBL0_MVP17_Req_Flank_Memory */


#define uint8_t_rd_LI0_TBL0_MVP17_Req_Flank_Memory() \
    ((uint8_t)  (((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Req_Flank_Memory_BYTE_OFFSET]) >> 3U) & 0x03U))


#define uint8_t_wr_LI0_TBL0_MVP17_Req_Flank_Memory(A) \
    { \
    g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Req_Flank_Memory_BYTE_OFFSET] = \
    (uint8_t)((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Req_Flank_Memory_BYTE_OFFSET] & 0xe7U) | \
    (((A) << 3U) & 0x18U)); \
    }
/* static access macros for signal LI0_TBL0_MVP17_Req_Active_Flank_Switch */


#define uint8_t_rd_LI0_TBL0_MVP17_Req_Active_Flank_Switch() \
    ((uint8_t)  (((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Req_Active_Flank_Switch_BYTE_OFFSET]) >> 5U) & 0x03U))


#define uint8_t_wr_LI0_TBL0_MVP17_Req_Active_Flank_Switch(A) \
    { \
    g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Req_Active_Flank_Switch_BYTE_OFFSET] = \
    (uint8_t)((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Req_Active_Flank_Switch_BYTE_OFFSET] & 0x9fU) | \
    (((A) << 5U) & 0x60U)); \
    }
/* static access macros for signal LI0_TBL0_MVP17_Req_Active_Flank_Ctrl */


#define uint8_t_rd_LI0_TBL0_MVP17_Req_Active_Flank_Ctrl() \
    ((uint8_t)  (((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Req_Active_Flank_Ctrl_BYTE_OFFSET]) >> 0U) & 0x07U))


#define uint8_t_wr_LI0_TBL0_MVP17_Req_Active_Flank_Ctrl(A) \
    { \
    g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Req_Active_Flank_Ctrl_BYTE_OFFSET] = \
    (uint8_t)((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Req_Active_Flank_Ctrl_BYTE_OFFSET] & 0xf8U) | \
    (((A) << 0U) & 0x07U)); \
    }
/* static access macros for signal LI0_TBL0_MVP17_Req_Active_Flank_Sensitivity */


#define uint8_t_rd_LI0_TBL0_MVP17_Req_Active_Flank_Sensitivity() \
    ((uint8_t)  (((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Req_Active_Flank_Sensitivity_BYTE_OFFSET]) >> 3U) & 0x03U))


#define uint8_t_wr_LI0_TBL0_MVP17_Req_Active_Flank_Sensitivity(A) \
    { \
    g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Req_Active_Flank_Sensitivity_BYTE_OFFSET] = \
    (uint8_t)((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Req_Active_Flank_Sensitivity_BYTE_OFFSET] & 0xe7U) | \
    (((A) << 3U) & 0x18U)); \
    }
/* static access macros for signal LI0_TBL0_MVP17_Req_Adaptive_Flank_Switch */


#define uint8_t_rd_LI0_TBL0_MVP17_Req_Adaptive_Flank_Switch() \
    ((uint8_t)  (((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Req_Adaptive_Flank_Switch_BYTE_OFFSET]) >> 5U) & 0x03U))


#define uint8_t_wr_LI0_TBL0_MVP17_Req_Adaptive_Flank_Switch(A) \
    { \
    g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Req_Adaptive_Flank_Switch_BYTE_OFFSET] = \
    (uint8_t)((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Req_Adaptive_Flank_Switch_BYTE_OFFSET] & 0x9fU) | \
    (((A) << 5U) & 0x60U)); \
    }
/* static access macros for signal LI0_TBL0_MVP17_Req_PressEn */


#define BOOL_rd_LI0_TBL0_MVP17_Req_PressEn() \
    (LIN_TEST_BIT(g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Req_PressEn_BYTE_OFFSET], \
    LIN_LI0_TBL0_MVP17_Req_PressEn_BIT_OFFSET))

#define BOOL_wr_LI0_TBL0_MVP17_Req_PressEn(A) \
    {(A) ? \
    (LIN_SET_BIT(g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Req_PressEn_BYTE_OFFSET], \
    LIN_LI0_TBL0_MVP17_Req_PressEn_BIT_OFFSET)):\
    (LIN_CLEAR_BIT(g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Req_PressEn_BYTE_OFFSET], \
    LIN_LI0_TBL0_MVP17_Req_PressEn_BIT_OFFSET));\
    }
/* static access macros for signal LI0_TBL0_MVP17_Pressure0 */


#define uint16_t_rd_LI0_TBL0_MVP17_Pressure0() \
    ((uint16_t)  (((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Pressure0_BYTE_OFFSET] + (g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Pressure0_BYTE_OFFSET + 1U] << 8U)) >> 0U) & 0xffffU))

#define uint16_t_wr_LI0_TBL0_MVP17_Pressure0(A) \
    { \
    g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Pressure0_BYTE_OFFSET] = \
    (uint8_t)((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Pressure0_BYTE_OFFSET] & 0x00U) | \
(((A) << 0U) & 0xffU)); \
    g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Pressure0_BYTE_OFFSET + 1U] = \
    (uint8_t)((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Pressure0_BYTE_OFFSET + 1U] & 0x00U) | \
(((A) >> 8U) & 0xffU)); \
    }
/* static access macros for signal LI0_TBL0_MVP17_Pressure1 */


#define uint16_t_rd_LI0_TBL0_MVP17_Pressure1() \
    ((uint16_t)  (((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Pressure1_BYTE_OFFSET] + (g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Pressure1_BYTE_OFFSET + 1U] << 8U)) >> 0U) & 0xffffU))

#define uint16_t_wr_LI0_TBL0_MVP17_Pressure1(A) \
    { \
    g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Pressure1_BYTE_OFFSET] = \
    (uint8_t)((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Pressure1_BYTE_OFFSET] & 0x00U) | \
(((A) << 0U) & 0xffU)); \
    g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Pressure1_BYTE_OFFSET + 1U] = \
    (uint8_t)((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Pressure1_BYTE_OFFSET + 1U] & 0x00U) | \
(((A) >> 8U) & 0xffU)); \
    }
/* static access macros for signal LI0_TBL0_MVP17_Pressure2 */


#define uint16_t_rd_LI0_TBL0_MVP17_Pressure2() \
    ((uint16_t)  (((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Pressure2_BYTE_OFFSET] + (g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Pressure2_BYTE_OFFSET + 1U] << 8U)) >> 0U) & 0xffffU))

#define uint16_t_wr_LI0_TBL0_MVP17_Pressure2(A) \
    { \
    g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Pressure2_BYTE_OFFSET] = \
    (uint8_t)((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Pressure2_BYTE_OFFSET] & 0x00U) | \
(((A) << 0U) & 0xffU)); \
    g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Pressure2_BYTE_OFFSET + 1U] = \
    (uint8_t)((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Pressure2_BYTE_OFFSET + 1U] & 0x00U) | \
(((A) >> 8U) & 0xffU)); \
    }
/* static access macros for signal LI0_TBL0_MVP17_Pressure3 */


#define uint16_t_rd_LI0_TBL0_MVP17_Pressure3() \
    ((uint16_t)  (((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Pressure3_BYTE_OFFSET] + (g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Pressure3_BYTE_OFFSET + 1U] << 8U)) >> 0U) & 0xffffU))

#define uint16_t_wr_LI0_TBL0_MVP17_Pressure3(A) \
    { \
    g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Pressure3_BYTE_OFFSET] = \
    (uint8_t)((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Pressure3_BYTE_OFFSET] & 0x00U) | \
(((A) << 0U) & 0xffU)); \
    g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Pressure3_BYTE_OFFSET + 1U] = \
    (uint8_t)((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Pressure3_BYTE_OFFSET + 1U] & 0x00U) | \
(((A) >> 8U) & 0xffU)); \
    }
/* static access macros for signal LI0_TBL0_MVP17_Pressure4 */


#define uint16_t_rd_LI0_TBL0_MVP17_Pressure4() \
    ((uint16_t)  (((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Pressure4_BYTE_OFFSET] + (g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Pressure4_BYTE_OFFSET + 1U] << 8U)) >> 0U) & 0xffffU))

#define uint16_t_wr_LI0_TBL0_MVP17_Pressure4(A) \
    { \
    g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Pressure4_BYTE_OFFSET] = \
    (uint8_t)((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Pressure4_BYTE_OFFSET] & 0x00U) | \
(((A) << 0U) & 0xffU)); \
    g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Pressure4_BYTE_OFFSET + 1U] = \
    (uint8_t)((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Pressure4_BYTE_OFFSET + 1U] & 0x00U) | \
(((A) >> 8U) & 0xffU)); \
    }
/* static access macros for signal LI0_TBL0_MVP17_Pressure5 */


#define uint16_t_rd_LI0_TBL0_MVP17_Pressure5() \
    ((uint16_t)  (((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Pressure5_BYTE_OFFSET] + (g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Pressure5_BYTE_OFFSET + 1U] << 8U)) >> 0U) & 0xffffU))

#define uint16_t_wr_LI0_TBL0_MVP17_Pressure5(A) \
    { \
    g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Pressure5_BYTE_OFFSET] = \
    (uint8_t)((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Pressure5_BYTE_OFFSET] & 0x00U) | \
(((A) << 0U) & 0xffU)); \
    g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Pressure5_BYTE_OFFSET + 1U] = \
    (uint8_t)((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Pressure5_BYTE_OFFSET + 1U] & 0x00U) | \
(((A) >> 8U) & 0xffU)); \
    }
/* static access macros for signal LI0_TBL0_MVP17_Pressure6 */


#define uint16_t_rd_LI0_TBL0_MVP17_Pressure6() \
    ((uint16_t)  (((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Pressure6_BYTE_OFFSET] + (g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Pressure6_BYTE_OFFSET + 1U] << 8U)) >> 0U) & 0xffffU))

#define uint16_t_wr_LI0_TBL0_MVP17_Pressure6(A) \
    { \
    g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Pressure6_BYTE_OFFSET] = \
    (uint8_t)((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Pressure6_BYTE_OFFSET] & 0x00U) | \
(((A) << 0U) & 0xffU)); \
    g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Pressure6_BYTE_OFFSET + 1U] = \
    (uint8_t)((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Pressure6_BYTE_OFFSET + 1U] & 0x00U) | \
(((A) >> 8U) & 0xffU)); \
    }
/* static access macros for signal LI0_TBL0_MVP17_Pressure7 */


#define uint16_t_rd_LI0_TBL0_MVP17_Pressure7() \
    ((uint16_t)  (((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Pressure7_BYTE_OFFSET] + (g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Pressure7_BYTE_OFFSET + 1U] << 8U)) >> 0U) & 0xffffU))

#define uint16_t_wr_LI0_TBL0_MVP17_Pressure7(A) \
    { \
    g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Pressure7_BYTE_OFFSET] = \
    (uint8_t)((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Pressure7_BYTE_OFFSET] & 0x00U) | \
(((A) << 0U) & 0xffU)); \
    g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Pressure7_BYTE_OFFSET + 1U] = \
    (uint8_t)((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Pressure7_BYTE_OFFSET + 1U] & 0x00U) | \
(((A) >> 8U) & 0xffU)); \
    }
/* static access macros for signal LI0_TBL0_MVP17_Pressure8 */


#define uint16_t_rd_LI0_TBL0_MVP17_Pressure8() \
    ((uint16_t)  (((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Pressure8_BYTE_OFFSET] + (g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Pressure8_BYTE_OFFSET + 1U] << 8U)) >> 0U) & 0xffffU))

#define uint16_t_wr_LI0_TBL0_MVP17_Pressure8(A) \
    { \
    g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Pressure8_BYTE_OFFSET] = \
    (uint8_t)((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Pressure8_BYTE_OFFSET] & 0x00U) | \
(((A) << 0U) & 0xffU)); \
    g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Pressure8_BYTE_OFFSET + 1U] = \
    (uint8_t)((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Pressure8_BYTE_OFFSET + 1U] & 0x00U) | \
(((A) >> 8U) & 0xffU)); \
    }
/* static access macros for signal LI0_TBL0_MVP17_Pressure9 */


#define uint16_t_rd_LI0_TBL0_MVP17_Pressure9() \
    ((uint16_t)  (((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Pressure9_BYTE_OFFSET] + (g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Pressure9_BYTE_OFFSET + 1U] << 8U)) >> 0U) & 0xffffU))

#define uint16_t_wr_LI0_TBL0_MVP17_Pressure9(A) \
    { \
    g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Pressure9_BYTE_OFFSET] = \
    (uint8_t)((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Pressure9_BYTE_OFFSET] & 0x00U) | \
(((A) << 0U) & 0xffU)); \
    g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Pressure9_BYTE_OFFSET + 1U] = \
    (uint8_t)((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Pressure9_BYTE_OFFSET + 1U] & 0x00U) | \
(((A) >> 8U) & 0xffU)); \
    }
/* static access macros for signal LI0_TBL0_MVP17_Pressure10 */


#define uint16_t_rd_LI0_TBL0_MVP17_Pressure10() \
    ((uint16_t)  (((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Pressure10_BYTE_OFFSET] + (g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Pressure10_BYTE_OFFSET + 1U] << 8U)) >> 0U) & 0xffffU))

#define uint16_t_wr_LI0_TBL0_MVP17_Pressure10(A) \
    { \
    g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Pressure10_BYTE_OFFSET] = \
    (uint8_t)((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Pressure10_BYTE_OFFSET] & 0x00U) | \
(((A) << 0U) & 0xffU)); \
    g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Pressure10_BYTE_OFFSET + 1U] = \
    (uint8_t)((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Pressure10_BYTE_OFFSET + 1U] & 0x00U) | \
(((A) >> 8U) & 0xffU)); \
    }
/* static access macros for signal LI0_TBL0_Sensor_Temperature0 */


#define uint8_t_rd_LI0_TBL0_Sensor_Temperature0() \
    ((uint8_t)  (((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_Sensor_Temperature0_BYTE_OFFSET]) >> 0U) & 0xffU))


#define uint8_t_wr_LI0_TBL0_Sensor_Temperature0(A) \
    { \
    g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_Sensor_Temperature0_BYTE_OFFSET] = \
    (uint8_t)((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_Sensor_Temperature0_BYTE_OFFSET] & 0x00U) | \
    (((A) << 0U) & 0xffU)); \
    }
/* static access macros for signal LI0_TBL0_Sensor_Temperature1 */


#define uint8_t_rd_LI0_TBL0_Sensor_Temperature1() \
    ((uint8_t)  (((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_Sensor_Temperature1_BYTE_OFFSET]) >> 0U) & 0xffU))


#define uint8_t_wr_LI0_TBL0_Sensor_Temperature1(A) \
    { \
    g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_Sensor_Temperature1_BYTE_OFFSET] = \
    (uint8_t)((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_Sensor_Temperature1_BYTE_OFFSET] & 0x00U) | \
    (((A) << 0U) & 0xffU)); \
    }
/* static access macros for signal LI0_TBL0_Sensor_Temperature2 */


#define uint8_t_rd_LI0_TBL0_Sensor_Temperature2() \
    ((uint8_t)  (((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_Sensor_Temperature2_BYTE_OFFSET]) >> 0U) & 0xffU))


#define uint8_t_wr_LI0_TBL0_Sensor_Temperature2(A) \
    { \
    g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_Sensor_Temperature2_BYTE_OFFSET] = \
    (uint8_t)((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_Sensor_Temperature2_BYTE_OFFSET] & 0x00U) | \
    (((A) << 0U) & 0xffU)); \
    }
/* static access macros for signal LI0_TBL0_Sensor_Temperature3 */


#define uint8_t_rd_LI0_TBL0_Sensor_Temperature3() \
    ((uint8_t)  (((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_Sensor_Temperature3_BYTE_OFFSET]) >> 0U) & 0xffU))


#define uint8_t_wr_LI0_TBL0_Sensor_Temperature3(A) \
    { \
    g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_Sensor_Temperature3_BYTE_OFFSET] = \
    (uint8_t)((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_Sensor_Temperature3_BYTE_OFFSET] & 0x00U) | \
    (((A) << 0U) & 0xffU)); \
    }
/* static access macros for signal LI0_TBL0_Sensor_Temperature4 */


#define uint8_t_rd_LI0_TBL0_Sensor_Temperature4() \
    ((uint8_t)  (((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_Sensor_Temperature4_BYTE_OFFSET]) >> 0U) & 0xffU))


#define uint8_t_wr_LI0_TBL0_Sensor_Temperature4(A) \
    { \
    g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_Sensor_Temperature4_BYTE_OFFSET] = \
    (uint8_t)((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_Sensor_Temperature4_BYTE_OFFSET] & 0x00U) | \
    (((A) << 0U) & 0xffU)); \
    }
/* static access macros for signal LI0_TBL0_Sensor_Temperature5 */


#define uint8_t_rd_LI0_TBL0_Sensor_Temperature5() \
    ((uint8_t)  (((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_Sensor_Temperature5_BYTE_OFFSET]) >> 0U) & 0xffU))


#define uint8_t_wr_LI0_TBL0_Sensor_Temperature5(A) \
    { \
    g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_Sensor_Temperature5_BYTE_OFFSET] = \
    (uint8_t)((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_Sensor_Temperature5_BYTE_OFFSET] & 0x00U) | \
    (((A) << 0U) & 0xffU)); \
    }
/* static access macros for signal LI0_TBL0_Sensor_Temperature6 */


#define uint8_t_rd_LI0_TBL0_Sensor_Temperature6() \
    ((uint8_t)  (((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_Sensor_Temperature6_BYTE_OFFSET]) >> 0U) & 0xffU))


#define uint8_t_wr_LI0_TBL0_Sensor_Temperature6(A) \
    { \
    g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_Sensor_Temperature6_BYTE_OFFSET] = \
    (uint8_t)((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_Sensor_Temperature6_BYTE_OFFSET] & 0x00U) | \
    (((A) << 0U) & 0xffU)); \
    }
/* static access macros for signal LI0_TBL0_Sensor_Temperature7 */


#define uint8_t_rd_LI0_TBL0_Sensor_Temperature7() \
    ((uint8_t)  (((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_Sensor_Temperature7_BYTE_OFFSET]) >> 0U) & 0xffU))


#define uint8_t_wr_LI0_TBL0_Sensor_Temperature7(A) \
    { \
    g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_Sensor_Temperature7_BYTE_OFFSET] = \
    (uint8_t)((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_Sensor_Temperature7_BYTE_OFFSET] & 0x00U) | \
    (((A) << 0U) & 0xffU)); \
    }
/* static access macros for signal LI0_TBL0_MVP17_State_LumbarMemory_lowBladderPressure */


#define uint16_t_rd_LI0_TBL0_MVP17_State_LumbarMemory_lowBladderPressure() \
    ((uint16_t)  (((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_State_LumbarMemory_lowBladderPressure_BYTE_OFFSET] + (g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_State_LumbarMemory_lowBladderPressure_BYTE_OFFSET + 1U] << 8U)) >> 0U) & 0xffffU))

#define uint16_t_wr_LI0_TBL0_MVP17_State_LumbarMemory_lowBladderPressure(A) \
    { \
    g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_State_LumbarMemory_lowBladderPressure_BYTE_OFFSET] = \
    (uint8_t)((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_State_LumbarMemory_lowBladderPressure_BYTE_OFFSET] & 0x00U) | \
(((A) << 0U) & 0xffU)); \
    g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_State_LumbarMemory_lowBladderPressure_BYTE_OFFSET + 1U] = \
    (uint8_t)((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_State_LumbarMemory_lowBladderPressure_BYTE_OFFSET + 1U] & 0x00U) | \
(((A) >> 8U) & 0xffU)); \
    }
/* static access macros for signal LI0_TBL0_MVP17_State_LumbarMemory_UpBladderPressure */


#define uint16_t_rd_LI0_TBL0_MVP17_State_LumbarMemory_UpBladderPressure() \
    ((uint16_t)  (((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_State_LumbarMemory_UpBladderPressure_BYTE_OFFSET] + (g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_State_LumbarMemory_UpBladderPressure_BYTE_OFFSET + 1U] << 8U)) >> 0U) & 0xffffU))

#define uint16_t_wr_LI0_TBL0_MVP17_State_LumbarMemory_UpBladderPressure(A) \
    { \
    g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_State_LumbarMemory_UpBladderPressure_BYTE_OFFSET] = \
    (uint8_t)((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_State_LumbarMemory_UpBladderPressure_BYTE_OFFSET] & 0x00U) | \
(((A) << 0U) & 0xffU)); \
    g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_State_LumbarMemory_UpBladderPressure_BYTE_OFFSET + 1U] = \
    (uint8_t)((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_State_LumbarMemory_UpBladderPressure_BYTE_OFFSET + 1U] & 0x00U) | \
(((A) >> 8U) & 0xffU)); \
    }
/* static access macros for signal LI0_TBL0_MVP17_State_FlankMemory_LeftPressure */


#define uint16_t_rd_LI0_TBL0_MVP17_State_FlankMemory_LeftPressure() \
    ((uint16_t)  (((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_State_FlankMemory_LeftPressure_BYTE_OFFSET] + (g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_State_FlankMemory_LeftPressure_BYTE_OFFSET + 1U] << 8U)) >> 0U) & 0xffffU))

#define uint16_t_wr_LI0_TBL0_MVP17_State_FlankMemory_LeftPressure(A) \
    { \
    g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_State_FlankMemory_LeftPressure_BYTE_OFFSET] = \
    (uint8_t)((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_State_FlankMemory_LeftPressure_BYTE_OFFSET] & 0x00U) | \
(((A) << 0U) & 0xffU)); \
    g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_State_FlankMemory_LeftPressure_BYTE_OFFSET + 1U] = \
    (uint8_t)((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_State_FlankMemory_LeftPressure_BYTE_OFFSET + 1U] & 0x00U) | \
(((A) >> 8U) & 0xffU)); \
    }
/* static access macros for signal LI0_TBL0_MVP17_State_FlankMemory_RigntPressure */


#define uint16_t_rd_LI0_TBL0_MVP17_State_FlankMemory_RigntPressure() \
    ((uint16_t)  (((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_State_FlankMemory_RigntPressure_BYTE_OFFSET] + (g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_State_FlankMemory_RigntPressure_BYTE_OFFSET + 1U] << 8U)) >> 0U) & 0xffffU))

#define uint16_t_wr_LI0_TBL0_MVP17_State_FlankMemory_RigntPressure(A) \
    { \
    g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_State_FlankMemory_RigntPressure_BYTE_OFFSET] = \
    (uint8_t)((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_State_FlankMemory_RigntPressure_BYTE_OFFSET] & 0x00U) | \
(((A) << 0U) & 0xffU)); \
    g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_State_FlankMemory_RigntPressure_BYTE_OFFSET + 1U] = \
    (uint8_t)((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_State_FlankMemory_RigntPressure_BYTE_OFFSET + 1U] & 0x00U) | \
(((A) >> 8U) & 0xffU)); \
    }
/* static access macros for signal LI0_TBL0_FK_MassageMode */


#define uint8_t_rd_LI0_TBL0_FK_MassageMode() \
    ((uint8_t)  (((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_FK_MassageMode_BYTE_OFFSET]) >> 0U) & 0x07U))


#define uint8_t_wr_LI0_TBL0_FK_MassageMode(A) \
    { \
    g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_FK_MassageMode_BYTE_OFFSET] = \
    (uint8_t)((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_FK_MassageMode_BYTE_OFFSET] & 0xf8U) | \
    (((A) << 0U) & 0x07U)); \
    }
/* static access macros for signal LI0_TBL0_FK_MassageGrade */


#define uint8_t_rd_LI0_TBL0_FK_MassageGrade() \
    ((uint8_t)  (((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_FK_MassageGrade_BYTE_OFFSET]) >> 3U) & 0x03U))


#define uint8_t_wr_LI0_TBL0_FK_MassageGrade(A) \
    { \
    g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_FK_MassageGrade_BYTE_OFFSET] = \
    (uint8_t)((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_FK_MassageGrade_BYTE_OFFSET] & 0xe7U) | \
    (((A) << 3U) & 0x18U)); \
    }
/* static access macros for signal LI0_TBL0_MVP17_State_MassageSwitch */


#define uint8_t_rd_LI0_TBL0_MVP17_State_MassageSwitch() \
    ((uint8_t)  (((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_State_MassageSwitch_BYTE_OFFSET]) >> 5U) & 0x03U))


#define uint8_t_wr_LI0_TBL0_MVP17_State_MassageSwitch(A) \
    { \
    g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_State_MassageSwitch_BYTE_OFFSET] = \
    (uint8_t)((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_State_MassageSwitch_BYTE_OFFSET] & 0x9fU) | \
    (((A) << 5U) & 0x60U)); \
    }
/* static access macros for signal LI0_TBL0_MVP17_ValveFaultState */


#define uint8_t_rd_LI0_TBL0_MVP17_ValveFaultState() \
    ((uint8_t)  (((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_ValveFaultState_BYTE_OFFSET]) >> 0U) & 0x07U))


#define uint8_t_wr_LI0_TBL0_MVP17_ValveFaultState(A) \
    { \
    g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_ValveFaultState_BYTE_OFFSET] = \
    (uint8_t)((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_ValveFaultState_BYTE_OFFSET] & 0xf8U) | \
    (((A) << 0U) & 0x07U)); \
    }
/* static access macros for signal LI0_TBL0_MVP17_PumpFaultState */


#define uint8_t_rd_LI0_TBL0_MVP17_PumpFaultState() \
    ((uint8_t)  (((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_PumpFaultState_BYTE_OFFSET]) >> 3U) & 0x07U))


#define uint8_t_wr_LI0_TBL0_MVP17_PumpFaultState(A) \
    { \
    g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_PumpFaultState_BYTE_OFFSET] = \
    (uint8_t)((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_PumpFaultState_BYTE_OFFSET] & 0xc7U) | \
    (((A) << 3U) & 0x38U)); \
    }
/* static access macros for signal LI0_TBL0_MVP17_Response_Error */


#define BOOL_rd_LI0_TBL0_MVP17_Response_Error() \
    (LIN_TEST_BIT(g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Response_Error_BYTE_OFFSET], \
    LIN_LI0_TBL0_MVP17_Response_Error_BIT_OFFSET))

#define BOOL_wr_LI0_TBL0_MVP17_Response_Error(A) \
    {(A) ? \
    (LIN_SET_BIT(g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Response_Error_BYTE_OFFSET], \
    LIN_LI0_TBL0_MVP17_Response_Error_BIT_OFFSET)):\
    (LIN_CLEAR_BIT(g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_Response_Error_BYTE_OFFSET], \
    LIN_LI0_TBL0_MVP17_Response_Error_BIT_OFFSET));\
    }
/* static access macros for signal LI0_TBL0_MVP17_BattVolFaultState */


#define uint8_t_rd_LI0_TBL0_MVP17_BattVolFaultState() \
    ((uint8_t)  (((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_BattVolFaultState_BYTE_OFFSET] + (g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_BattVolFaultState_BYTE_OFFSET + 1U] << 8U)) >> 7U) & 0xffU))

#define uint8_t_wr_LI0_TBL0_MVP17_BattVolFaultState(A) \
    { \
    g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_BattVolFaultState_BYTE_OFFSET] = \
    (uint8_t)((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_BattVolFaultState_BYTE_OFFSET] & 0x7fU) | \
    (((A) << 7U) & 0x80U)); \
    g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_BattVolFaultState_BYTE_OFFSET + 1U] = \
    (uint8_t)((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_MVP17_BattVolFaultState_BYTE_OFFSET + 1U] & 0x80U) | \
(((A) >> 1U) & 0x7fU)); \
    }
/* static access macros for signal LI0_TBL0_Sensor_Temperature8 */


#define uint8_t_rd_LI0_TBL0_Sensor_Temperature8() \
    ((uint8_t)  (((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_Sensor_Temperature8_BYTE_OFFSET]) >> 0U) & 0xffU))


#define uint8_t_wr_LI0_TBL0_Sensor_Temperature8(A) \
    { \
    g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_Sensor_Temperature8_BYTE_OFFSET] = \
    (uint8_t)((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_Sensor_Temperature8_BYTE_OFFSET] & 0x00U) | \
    (((A) << 0U) & 0xffU)); \
    }
/* static access macros for signal LI0_TBL0_Sensor_Temperature9 */


#define uint8_t_rd_LI0_TBL0_Sensor_Temperature9() \
    ((uint8_t)  (((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_Sensor_Temperature9_BYTE_OFFSET]) >> 0U) & 0xffU))


#define uint8_t_wr_LI0_TBL0_Sensor_Temperature9(A) \
    { \
    g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_Sensor_Temperature9_BYTE_OFFSET] = \
    (uint8_t)((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_Sensor_Temperature9_BYTE_OFFSET] & 0x00U) | \
    (((A) << 0U) & 0xffU)); \
    }
/* static access macros for signal LI0_TBL0_Sensor_Temperature10 */


#define uint8_t_rd_LI0_TBL0_Sensor_Temperature10() \
    ((uint8_t)  (((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_Sensor_Temperature10_BYTE_OFFSET]) >> 0U) & 0xffU))


#define uint8_t_wr_LI0_TBL0_Sensor_Temperature10(A) \
    { \
    g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_Sensor_Temperature10_BYTE_OFFSET] = \
    (uint8_t)((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_Sensor_Temperature10_BYTE_OFFSET] & 0x00U) | \
    (((A) << 0U) & 0xffU)); \
    }
/* static access macros for signal LI0_TBL0_Ntc_Temperature */


#define uint8_t_rd_LI0_TBL0_Ntc_Temperature() \
    ((uint8_t)  (((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_Ntc_Temperature_BYTE_OFFSET]) >> 0U) & 0xffU))


#define uint8_t_wr_LI0_TBL0_Ntc_Temperature(A) \
    { \
    g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_Ntc_Temperature_BYTE_OFFSET] = \
    (uint8_t)((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_Ntc_Temperature_BYTE_OFFSET] & 0x00U) | \
    (((A) << 0U) & 0xffU)); \
    }
/* static access macros for signal LI0_TBL0_Massage_Dot1 */


#define BOOL_rd_LI0_TBL0_Massage_Dot1() \
    (LIN_TEST_BIT(g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_Massage_Dot1_BYTE_OFFSET], \
    LIN_LI0_TBL0_Massage_Dot1_BIT_OFFSET))

#define BOOL_wr_LI0_TBL0_Massage_Dot1(A) \
    {(A) ? \
    (LIN_SET_BIT(g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_Massage_Dot1_BYTE_OFFSET], \
    LIN_LI0_TBL0_Massage_Dot1_BIT_OFFSET)):\
    (LIN_CLEAR_BIT(g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_Massage_Dot1_BYTE_OFFSET], \
    LIN_LI0_TBL0_Massage_Dot1_BIT_OFFSET));\
    }
/* static access macros for signal LI0_TBL0_Massage_Dot2 */


#define BOOL_rd_LI0_TBL0_Massage_Dot2() \
    (LIN_TEST_BIT(g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_Massage_Dot2_BYTE_OFFSET], \
    LIN_LI0_TBL0_Massage_Dot2_BIT_OFFSET))

#define BOOL_wr_LI0_TBL0_Massage_Dot2(A) \
    {(A) ? \
    (LIN_SET_BIT(g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_Massage_Dot2_BYTE_OFFSET], \
    LIN_LI0_TBL0_Massage_Dot2_BIT_OFFSET)):\
    (LIN_CLEAR_BIT(g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_Massage_Dot2_BYTE_OFFSET], \
    LIN_LI0_TBL0_Massage_Dot2_BIT_OFFSET));\
    }
/* static access macros for signal LI0_TBL0_Massage_Dot3 */


#define BOOL_rd_LI0_TBL0_Massage_Dot3() \
    (LIN_TEST_BIT(g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_Massage_Dot3_BYTE_OFFSET], \
    LIN_LI0_TBL0_Massage_Dot3_BIT_OFFSET))

#define BOOL_wr_LI0_TBL0_Massage_Dot3(A) \
    {(A) ? \
    (LIN_SET_BIT(g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_Massage_Dot3_BYTE_OFFSET], \
    LIN_LI0_TBL0_Massage_Dot3_BIT_OFFSET)):\
    (LIN_CLEAR_BIT(g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_Massage_Dot3_BYTE_OFFSET], \
    LIN_LI0_TBL0_Massage_Dot3_BIT_OFFSET));\
    }
/* static access macros for signal LI0_TBL0_Massage_Dot4 */


#define BOOL_rd_LI0_TBL0_Massage_Dot4() \
    (LIN_TEST_BIT(g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_Massage_Dot4_BYTE_OFFSET], \
    LIN_LI0_TBL0_Massage_Dot4_BIT_OFFSET))

#define BOOL_wr_LI0_TBL0_Massage_Dot4(A) \
    {(A) ? \
    (LIN_SET_BIT(g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_Massage_Dot4_BYTE_OFFSET], \
    LIN_LI0_TBL0_Massage_Dot4_BIT_OFFSET)):\
    (LIN_CLEAR_BIT(g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_Massage_Dot4_BYTE_OFFSET], \
    LIN_LI0_TBL0_Massage_Dot4_BIT_OFFSET));\
    }
/* static access macros for signal LI0_TBL0_Massage_Dot5 */


#define BOOL_rd_LI0_TBL0_Massage_Dot5() \
    (LIN_TEST_BIT(g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_Massage_Dot5_BYTE_OFFSET], \
    LIN_LI0_TBL0_Massage_Dot5_BIT_OFFSET))

#define BOOL_wr_LI0_TBL0_Massage_Dot5(A) \
    {(A) ? \
    (LIN_SET_BIT(g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_Massage_Dot5_BYTE_OFFSET], \
    LIN_LI0_TBL0_Massage_Dot5_BIT_OFFSET)):\
    (LIN_CLEAR_BIT(g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_Massage_Dot5_BYTE_OFFSET], \
    LIN_LI0_TBL0_Massage_Dot5_BIT_OFFSET));\
    }
/* static access macros for signal LI0_TBL0_Massage_Dot6 */


#define BOOL_rd_LI0_TBL0_Massage_Dot6() \
    (LIN_TEST_BIT(g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_Massage_Dot6_BYTE_OFFSET], \
    LIN_LI0_TBL0_Massage_Dot6_BIT_OFFSET))

#define BOOL_wr_LI0_TBL0_Massage_Dot6(A) \
    {(A) ? \
    (LIN_SET_BIT(g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_Massage_Dot6_BYTE_OFFSET], \
    LIN_LI0_TBL0_Massage_Dot6_BIT_OFFSET)):\
    (LIN_CLEAR_BIT(g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_Massage_Dot6_BYTE_OFFSET], \
    LIN_LI0_TBL0_Massage_Dot6_BIT_OFFSET));\
    }
/* static access macros for signal LI0_TBL0_Massage_Dot7 */


#define BOOL_rd_LI0_TBL0_Massage_Dot7() \
    (LIN_TEST_BIT(g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_Massage_Dot7_BYTE_OFFSET], \
    LIN_LI0_TBL0_Massage_Dot7_BIT_OFFSET))

#define BOOL_wr_LI0_TBL0_Massage_Dot7(A) \
    {(A) ? \
    (LIN_SET_BIT(g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_Massage_Dot7_BYTE_OFFSET], \
    LIN_LI0_TBL0_Massage_Dot7_BIT_OFFSET)):\
    (LIN_CLEAR_BIT(g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_Massage_Dot7_BYTE_OFFSET], \
    LIN_LI0_TBL0_Massage_Dot7_BIT_OFFSET));\
    }
/* static access macros for signal LI0_TBL0_Massage_Dot8 */


#define BOOL_rd_LI0_TBL0_Massage_Dot8() \
    (LIN_TEST_BIT(g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_Massage_Dot8_BYTE_OFFSET], \
    LIN_LI0_TBL0_Massage_Dot8_BIT_OFFSET))

#define BOOL_wr_LI0_TBL0_Massage_Dot8(A) \
    {(A) ? \
    (LIN_SET_BIT(g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_Massage_Dot8_BYTE_OFFSET], \
    LIN_LI0_TBL0_Massage_Dot8_BIT_OFFSET)):\
    (LIN_CLEAR_BIT(g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_Massage_Dot8_BYTE_OFFSET], \
    LIN_LI0_TBL0_Massage_Dot8_BIT_OFFSET));\
    }
/* static access macros for signal LI0_TBL0_Flank_Right */


#define uint8_t_rd_LI0_TBL0_Flank_Right() \
    ((uint8_t)  (((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_Flank_Right_BYTE_OFFSET]) >> 0U) & 0x0fU))


#define uint8_t_wr_LI0_TBL0_Flank_Right(A) \
    { \
    g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_Flank_Right_BYTE_OFFSET] = \
    (uint8_t)((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_Flank_Right_BYTE_OFFSET] & 0xf0U) | \
    (((A) << 0U) & 0x0fU)); \
    }
/* static access macros for signal LI0_TBL0_Flank_Left */


#define uint8_t_rd_LI0_TBL0_Flank_Left() \
    ((uint8_t)  (((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_Flank_Left_BYTE_OFFSET]) >> 4U) & 0x0fU))


#define uint8_t_wr_LI0_TBL0_Flank_Left(A) \
    { \
    g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_Flank_Left_BYTE_OFFSET] = \
    (uint8_t)((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_Flank_Left_BYTE_OFFSET] & 0x0fU) | \
    (((A) << 4U) & 0xf0U)); \
    }
/* static access macros for signal LI0_TBL0_Lumbar_UP */


#define uint8_t_rd_LI0_TBL0_Lumbar_UP() \
    ((uint8_t)  (((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_Lumbar_UP_BYTE_OFFSET]) >> 0U) & 0x0fU))


#define uint8_t_wr_LI0_TBL0_Lumbar_UP(A) \
    { \
    g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_Lumbar_UP_BYTE_OFFSET] = \
    (uint8_t)((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_Lumbar_UP_BYTE_OFFSET] & 0xf0U) | \
    (((A) << 0U) & 0x0fU)); \
    }
/* static access macros for signal LI0_TBL0_Lumbar_Down */


#define uint8_t_rd_LI0_TBL0_Lumbar_Down() \
    ((uint8_t)  (((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_Lumbar_Down_BYTE_OFFSET]) >> 4U) & 0x0fU))


#define uint8_t_wr_LI0_TBL0_Lumbar_Down(A) \
    { \
    g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_Lumbar_Down_BYTE_OFFSET] = \
    (uint8_t)((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_Lumbar_Down_BYTE_OFFSET] & 0x0fU) | \
    (((A) << 4U) & 0xf0U)); \
    }
/* static access macros for signal LI0_TBL0_Sensor_Bag1 */


#define uint8_t_rd_LI0_TBL0_Sensor_Bag1() \
    ((uint8_t)  (((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_Sensor_Bag1_BYTE_OFFSET]) >> 0U) & 0x0fU))


#define uint8_t_wr_LI0_TBL0_Sensor_Bag1(A) \
    { \
    g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_Sensor_Bag1_BYTE_OFFSET] = \
    (uint8_t)((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_Sensor_Bag1_BYTE_OFFSET] & 0xf0U) | \
    (((A) << 0U) & 0x0fU)); \
    }
/* static access macros for signal LI0_TBL0_Sensor_Bag2 */


#define uint8_t_rd_LI0_TBL0_Sensor_Bag2() \
    ((uint8_t)  (((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_Sensor_Bag2_BYTE_OFFSET]) >> 4U) & 0x0fU))


#define uint8_t_wr_LI0_TBL0_Sensor_Bag2(A) \
    { \
    g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_Sensor_Bag2_BYTE_OFFSET] = \
    (uint8_t)((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_Sensor_Bag2_BYTE_OFFSET] & 0x0fU) | \
    (((A) << 4U) & 0xf0U)); \
    }
/* static access macros for signal LI0_TBL0_Sensor_Bag3 */


#define uint8_t_rd_LI0_TBL0_Sensor_Bag3() \
    ((uint8_t)  (((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_Sensor_Bag3_BYTE_OFFSET]) >> 0U) & 0x0fU))


#define uint8_t_wr_LI0_TBL0_Sensor_Bag3(A) \
    { \
    g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_Sensor_Bag3_BYTE_OFFSET] = \
    (uint8_t)((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_Sensor_Bag3_BYTE_OFFSET] & 0xf0U) | \
    (((A) << 0U) & 0x0fU)); \
    }
/* static access macros for signal LI0_TBL0_Sensor_Bag4 */


#define uint8_t_rd_LI0_TBL0_Sensor_Bag4() \
    ((uint8_t)  (((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_Sensor_Bag4_BYTE_OFFSET]) >> 4U) & 0x0fU))


#define uint8_t_wr_LI0_TBL0_Sensor_Bag4(A) \
    { \
    g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_Sensor_Bag4_BYTE_OFFSET] = \
    (uint8_t)((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_Sensor_Bag4_BYTE_OFFSET] & 0x0fU) | \
    (((A) << 4U) & 0xf0U)); \
    }
/* static access macros for signal LI0_TBL0_GasStorage */


#define uint8_t_rd_LI0_TBL0_GasStorage() \
    ((uint8_t)  (((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_GasStorage_BYTE_OFFSET]) >> 0U) & 0x0fU))


#define uint8_t_wr_LI0_TBL0_GasStorage(A) \
    { \
    g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_GasStorage_BYTE_OFFSET] = \
    (uint8_t)((g_lin_protocol_ldf_cfg_array[LI0_Schedule_Index0].Frame_Buff_data_ptr[LIN_LI0_TBL0_GasStorage_BYTE_OFFSET] & 0xf0U) | \
    (((A) << 0U) & 0x0fU)); \
    }
/* INTERFACE MANAGEMENT */

/*FUNCTION**********************************************************************
 *
 * Function Name : l_ifc_init_interface
 * Description   : This static function call to dynamic function l_ifc_init()
 *
 * Implements    : l_ifc_init_interface_Class
 *END**************************************************************************/

#define l_ifc_init_LI0() l_ifc_init(LI0)

#define l_ifc_get_state_LI0() l_ifc_get_state(LI0)
#define l_ifc_Nm_Sleep_State_get    ((LIN_NODE_STATE_SLEEP_MODE == l_ifc_get_state(LI0))?1:0)



#define l_ifc_ld_init_LI0() ld_init(LI0)


#define l_ifc_tl_InstallCallback_Diag_Tx_Data_assignment_LI0(Func)  ld_InstallCallback(Commontl_proto_Callback_Diag_Tx_Data_assignment,Func)
#define l_ifc_tl_InstallCallback_Diag_Tx_Complete_LI0(Func)           ld_InstallCallback(Commontl_proto_Callback_Diag_Tx_Complete,Func)
#define l_ifc_tl_InstallCallback_Diag_Rx_Complete_LI0(Func)           ld_InstallCallback(Commontl_proto_Callback_Diag_Rx_Complete,Func)

#define l_ifc_tl_InstallCallback_Proprietary_Tx_Data_assignment_LI0(Func)  ld_InstallCallback(Commontl_proto_Callback_Proprietary_Tx_Data_assignment,Func)
#define l_ifc_tl_InstallCallback_Proprietary_Tx_Complete_LI0(Func)           ld_InstallCallback(Commontl_proto_Callback_Proprietary_Tx_Complete,Func)
#define l_ifc_tl_InstallCallback_Proprietary_Rx_Complete_LI0(Func)           ld_InstallCallback(Commontl_proto_Callback_Proprietary_Rx_Complete,Func)

#define l_ifc_tl_InstallCallback_App_Tx_Data_assignment_LI0(Func)  ld_ApplyIdInstallCallback(Commontl_proto_Callback_App_Tx_Data_assignment,Func)
#define l_ifc_tl_InstallCallback_App_Tx_Complete_LI0(Func)           ld_ApplyIdInstallCallback(Commontl_proto_Callback_App_Tx_Complete,Func)
#define l_ifc_tl_InstallCallback_App_Rx_Complete_LI0(Func)           ld_ApplyIdInstallCallback(Commontl_proto_Callback_App_Rx_Complete,Func)

/*FUNCTION**********************************************************************
 *
 * Function Name : l_ifc_wake_up_interface
 * Description   : This static function call to dynamic function l_ifc_wake_up()
 *
 * Implements    : l_ifc_wake_up_interface_Class
 *END**************************************************************************/

#define l_ifc_wake_up_LI0() l_ifc_wake_up(LI0)


/*FUNCTION**********************************************************************
 *
 * Function Name : l_ifc_read_status_interface
 * Description   : This static function call to dynamic function l_ifc_read_status()
 *
 * Implements    : l_ifc_read_status_interface_Class
 *END**************************************************************************/

#define l_ifc_read_status_LI0() l_ifc_read_status(LI0)

#define l_lld_timeout_service_LI0()  lin_lld_timeout_service(LI0)
/*FUNCTION**********************************************************************
 *
 * Function Name : l_lld_Id_Respone_Set_LI0
 * Description   : This function Enable which Node ID needs to be sent and received
 *
 * Implements    : ld_Set_id_Respone_En
 *END**************************************************************************/
extern void ld_Set_id_Respone_En(uint8_t OpScheduleTblIndex,uint8_t OpFrameIndex,uint8_t data);
#define l_lld_Id_Respone_Set_LI0(TblIndex,Frameindex,data)  ld_Set_id_Respone_En(TblIndex,Frameindex,data)
/*FUNCTION**********************************************************************
 *
 * Function Name : l_lld_Id_Stbl_use_index_Set_LI0
 * Description   : This function set which LIN schedule table is currently in use
 *
 * Implements    : ld_Set_lin_schedule_tbl_use_index
 *END**************************************************************************/
extern void ld_Set_lin_schedule_tbl_use_En(uint8_t OpScheduleTblIndex,uint8_t data);

#define l_lld_Id_Stbl_use_index_Set_LI0(TblIndex,data)  ld_Set_lin_schedule_tbl_use_En(TblIndex,data)
/*FUNCTION**********************************************************************
 *
 * Function Name : l_lld_Id_lin_ResponeErr_Status_Get_LI0
 * Description   : This function get the current LIN bus error status
 *
 * Implements    : ld_Get_lin_ResponeErr_Status
 *END**************************************************************************/

#define l_lld_Id_lin_ResponeErr_Status_Get_LI0()  ld_Get_lin_ResponeErr_Status()

#endif    /* _LIN_CFG_H_ */
