/*******************************************************************************
**                                                                            **
** Copyright (C) iSOFT   (2022)                                               **
**                                                                            **
** All rights reserved.                                                       **
**                                                                            **
** This document contains proprietary information belonging to iSOFT.         **
** Passing on and copying of this document, and communication                 **
** of its contents is not permitted without prior written authorization.      **
**                                                                            **
********************************************************************************
**                                                                            **
**  FILENAME    : Rte_Cbk.h                                                   **
**                                                                            **
**  Created on  :2025/05/29                                                        
**  Author      : Devin                                                       **
**  Vendor      :                                                             **
**  DESCRIPTION : If there is no RTE module, it is generated by COM           **
**                                                                            **
**  SPECIFICATION(S) :   AUTOSAR classic Platform 4.2.2                       **
**                                                                            **
*******************************************************************************/

#ifndef  RTE_CBK_H
#define  RTE_CBK_H

#include "ComStack_Types.h"


#endif


