/**
* @file        PduR_Cfg.h
* @brief       configuration header file for PduR
* @version     1.2.0
* @addtogroup  PduR
* @{
*/
/*====================================================================================================*
 * AngHui AUTOSAR BSW.
 *
 * Copyright(C) 2023 GuoKeAngHui Inc.
 *
 * All rights reserved.
 *
 * This file is part of AngHui AUTOSAR BSW, contains proprietary information.
 * Passing on and copying of this document, and communication of its contents
 * is not permitted without prior written authorization.
 *====================================================================================================*/

#ifndef  PDUR_CFG_H
#define  PDUR_CFG_H

 /*====================================================================================================*
 *                                           INCLUDE FILES                                          
 *====================================================================================================*/

/*====================================================================================================*
 *                                  SOURCE FILE VERSION INFORMATION
 *====================================================================================================*/
#define PDUR_CFG_VENDOR_ID               		    0U
#define PDUR_CFG_AR_RELEASE_MAJOR_VERSION		    4U
#define PDUR_CFG_AR_RELEASE_MINOR_VERSION		    2U
#define PDUR_CFG_AR_RELEASE_REVISION_VERSION	    2U
#define PDUR_CFG_SW_MAJOR_VERSION      			    1U
#define PDUR_CFG_SW_MINOR_VERSION      		    	2U
#define PDUR_CFG_SW_PATCH_VERSION      		    	0U

/*====================================================================================================*
 *                                         FILE VERSION CHECKS
 *====================================================================================================*/

 /*====================================================================================================*
 *                                   EXTERNAL FUNCTION DECLARATIONS
 *====================================================================================================*/

/*====================================================================================================*
 *                                           LOCAL TYPEDEFS
 *====================================================================================================*/

/*====================================================================================================*
 *                                            LOCAL MACROS
 *====================================================================================================*/
/* Zero cost operation only support */
#define PDUR_ZERO_COST_OPERATION         STD_OFF

/* Config Use DET or Not, Generated by Tool */
#define PDUR_DEV_ERROR_DETECT            STD_OFF

/* Enable support for MetaData handling in CAN-CAN-routing */
#define PDUR_META_DATA_SUPPORT           STD_OFF

/* If true the PduR_GetVersionInfo API is available */
#define PDUR_VERSION_INFO_API            STD_OFF

#define PDUR_BSW_MODULE_SUM             4

#define PDUR_CANIF_SUPPORT        STD_OFF
#define PDUR_CANTP_SUPPORT        STD_OFF
#define PDUR_J1939TP_SUPPORT      STD_OFF
#define PDUR_COM_SUPPORT          STD_ON
#define PDUR_DCM_SUPPORT          STD_ON
#define PDUR_J1939DCM_SUPPORT     STD_OFF
#define PDUR_IPDUM_SUPPORT        STD_OFF
#define PDUR_J1939RM_SUPPORT      STD_OFF
#define PDUR_LDCOM_SUPPORT        STD_OFF
#define PDUR_SECOC_SUPPORT        STD_OFF
#define PDUR_DBG_SUPPORT          STD_OFF
#define PDUR_CANNM_SUPPORT        STD_OFF
#define PDUR_OSEKNM_SUPPORT       STD_OFF
#define PDUR_LINIF_SUPPORT        STD_ON
#define PDUR_LINTP_SUPPORT        STD_ON
#define PDUR_FRIF_SUPPORT         STD_OFF
#define PDUR_FRNM_SUPPORT         STD_OFF
#define PDUR_SOAD_SUPPORT         STD_OFF
#define PDUR_SOADIF_SUPPORT       STD_OFF
#define PDUR_SOADTP_SUPPORT       STD_OFF

#define PDUR_TP_SUPPORT                        STD_ON
#define PDUR_UPMODE_SUPPORT                    STD_ON
#define PDUR_UPMODE_CANCEL_TRANSMIT            STD_OFF
#define PDUR_UPMODE_CHANGE_PARAMETER           STD_OFF
#define PDUR_UPMODE_CANCEL_RECEIVE             STD_OFF
#define PDUR_LOWER_SUPPORT                     STD_ON
#define PDUR_TX_CONFIRMATION                   STD_ON
#define PDUR_TRIGGER_TRANSMIT                  STD_ON

#define PDUR_COM_CANCEL_TRANSMIT           STD_OFF
#define PDUR_DCM_CANCEL_TRANSMIT           STD_OFF
#define PDUR_J1939DCM_CANCEL_TRANSMIT      STD_OFF
#define PDUR_J1939RM_CANCEL_TRANSMIT       STD_OFF
#define PDUR_LDCOM_CANCEL_TRANSMIT         STD_OFF
#define PDUR_SECOC_CANCEL_TRANSMIT         STD_OFF

#define PDUR_COM_CHANGE_PARAMETER          STD_OFF
#define PDUR_DCM_CHANGE_PARAMETER          STD_OFF
#define PDUR_J1939DCM_CHANGE_PARAMETER     STD_OFF
#define PDUR_LDCOM_CHANGE_PARAMETER        STD_OFF

#define PDUR_COM_CANCEL_RECEIVE            STD_OFF
#define PDUR_DCM_CANCEL_RECEIVE            STD_OFF
#define PDUR_J1939DCM_CANCEL_RECEIVE       STD_OFF
#define PDUR_LDCOM_CANCEL_RECEIVE          STD_OFF

#define PDUR_CANIF_TX_CONFIRMATION         STD_OFF
#define PDUR_CANIF_TRIGGER_TRANSMIT        STD_OFF

#define PDUR_LINIF_TX_CONFIRMATION         STD_ON
#define PDUR_LINIF_TRIGGER_TRANSMIT        STD_ON

#define PDUR_CANNM_TX_CONFIRMATION         STD_OFF
#define PDUR_CANNM_TRIGGER_TRANSMIT        STD_OFF

#define PDUR_OSEKNM_TX_CONFIRMATION        STD_OFF
#define PDUR_OSEKNM_TRIGGER_TRANSMIT       STD_OFF

#define PDUR_SECOC_TX_CONFIRMATION         STD_OFF

#define PDUR_IPDUM_TX_CONFIRMATION         STD_OFF
#define PDUR_IPDUM_TRIGGER_TRANSMIT        STD_OFF

#define PDUR_SOAD_TX_CONFIRMATION         STD_OFF
#define PDUR_SOAD_TRIGGER_TRANSMIT        STD_OFF

/* add other configer */
#define PDUR_SRC_PDU_SUM                  6
#define PduRConf_PduRSrcPdu_LinPdu_LinTpToPduR_MasterReq_Rx              0
#define PduRConf_PduRSrcPdu_LinPdu_DcmToPduR_SlaveResp_Tx              1
#define PduRConf_PduRSrcPdu_LinPdu_ComToPduR_DSMM_1_Tx              2
#define PduRConf_PduRSrcPdu_LinPdu_LinIfToPduR_ZCU_SMM_1_Rx              3
#define PduRConf_PduRSrcPdu_LinPdu_LinIfToPduR_ZCU_SMM_2_Rx              4
#define PduRConf_PduRSrcPdu_LinPdu_LinTpToPduR_FuncReq_Rx              5

#define PDUR_DEST_PDU_SUM                  6
#define PDUR_DEST_GATEWAY_TP_PDU_SUM       0
#define PduRConf_PduRDestPdu_LinPdu_PduRToDcm_MasterReq_Rx               0
#define PduRConf_PduRDestPdu_LinPdu_PduRToLinTp_SlaveResp_Tx               1
#define PduRConf_PduRDestPdu_LinPdu_PduRToLinIf_DSMM_1_Tx               2
#define PduRConf_PduRDestPdu_LinPdu_PduRToCom_ZCU_SMM_1_Rx               3
#define PduRConf_PduRDestPdu_LinPdu_PduRToCom_ZCU_SMM_2_Rx               4
#define PduRConf_PduRDestPdu_LinPdu_PduRToDcm_FuncReq_Rx               5

#define PDUR_ROUTING_PATH_GROUP_SUM                 0

#define PDUR_SRC_UP_MULTICAST_TX_IF_SUM              0/*up local mode(COM/DCM),for 1:n(n>1) if transmit*/
#define PDUR_SRC_UP_MULTICAST_TX_TP_SUM              0/*up local mode(COM/DCM),for 1:n(n>1) tp transmit*/
#define PDUR_GATEWAY_DIRECT_BUFFER_PDU_SUM           0/*used for gateway direct pdu which have configed buffer*/

#define PDUR_TP_BUFFER_SUM           0
#define PDUR_TX_BUFFER_SUM           0 /*just route dest pdu have the txbuffer*/

#define PDUR_DEFAULT_VALUE_LENGTH           0/*all dest pdu(PDUR_TRIGGERTRANSMIT) default value length*/
#define PDUR_DEFAULT_VALUE                  0 /*use default value pdu number*/



/*====================================================================================================*
 *                                           LOCAL CONSTANTS
 *====================================================================================================*/

/*====================================================================================================*
 *                                           LOCAL VARIABLES
 *====================================================================================================*/

/*====================================================================================================*
 *                                      LOCAL FUNCTION PROTOTYPES
 *====================================================================================================*/

/*====================================================================================================*
 *                                           LOCAL FUNCTIONS
 *====================================================================================================*/

/*====================================================================================================*
 *                                          GLOBAL FUNCTIONS
 *====================================================================================================*/

#ifdef __cplusplus
}
#endif
/** @} */

#endif  /* end of PDUR_CFG_H */
