/**************************************************************************************************/
/*                                                                                                */
/*   Project      :                                                                               */
/*   Type         :      H source file                                                            */
/*   Name         :      lin.h                                                                    */
/*   Instance     :                                                                               */
/*   Author       :      Ed                                                                       */
/*   Modify date  :      2025-04-11 11:08:33 AM                                                   */
/*   Description  :                                                                               */
/*                                                                                                */
/*                                                                                                */
/*   Compiler    :       KungFu32 IDE  [Version: V1.0.20.3]                                       */
/*   Hardware    :       ChipOn microcontroller KF32A Family [KF32A136KQT]                        */
/*   Version     :       V1.0                                                                     */
/*                                                                                                */
/*                                                                                                */
/*   All rights reserved. Distribution or duplication without previous written agreement of the   */
/*   owner prohibited.                                                                            */
/*                                                                                                */
/**************************************************************************************************/
/*
 * Copyright (c) 2015-2016, Freescale Semiconductor, Inc.
 * Copyright 2016-2017 NXP
 * All rights reserved.
 *
 * THIS SOFTWARE IS PROVIDED BY NXP "AS IS" AND ANY EXPRESSED OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL NXP OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
 * INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
 * IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
 * THE POSSIBILITY OF SUCH DAMAGE.
 */
/*!
 * @file lin.h
 *
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Directive 4.9, A function should be used in preference to a function-like
 * macro where they are interchangeable.
 * The macro is defined for callback functions or use for skeleton code.
 * This way is more efficient.
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 8.9, An object should be defined at block scope if its identifier
 * only appears in a single function.
 * Since array g_lin_hardware_ifc and timerGetTimeIntervalCallbackArr are defined and
 * initialized into lin_cfg.c and this file is generated by NCF tool cannot be placed
 * elsewhere.
 */


#ifndef APPLY_LIN_H
#define APPLY_LIN_H

/*!
 * @addtogroup lowlevel_group
 * @{
 */
#include "include.h"
#include "lin_driver.h"


/* *****************************************************************************
 * Definitions
 ******************************************************************************/
/* This macro is used only when transport layer is not used;
remove '#if' directive if needed it also when transport layer is enabled */
#if ((SUPPORT_TRANSPORT_LAYER != 1U) || (SUPPORT_DIAG_SERVICE != 1U))
#define UNUSED(x)   (void)(x)
#endif /* end (SUPPORT_TRANSPORT_LAYER != 1U) */

/* Define diagnostic services id */
#define SERVICE_ASSIGN_NAD                0xB0U      /*!< Assign NAD service */
#define SERVICE_ASSIGN_FRAME_ID           0xB1U      /*!< Assign frame id service */
#define SERVICE_READ_BY_IDENTIFY          0xB2U      /*!< Read by identify service */
#define SERVICE_CONDITIONAL_CHANGE_NAD    0xB3U      /*!< Conditional change NAD service */
#define SERVICE_SAVE_CONFIGURATION        0xB6U      /*!< Save configuration service */
#define SERVICE_ASSIGN_FRAME_ID_RANGE     0xB7U      /*!< Assign frame id range service */

#define SERVICE_READ_DATA_BY_IDENTIFY     0x22U      /*!< Service read data by identifier */
#define SERVICE_WRITE_DATA_BY_IDENTIFY    0x2EU      /*!< Service write data by identifier */
#define SERVICE_SESSION_CONTROL           0x10U      /*!< Service session control */
#define SERVICE_IO_CONTROL_BY_IDENTIFY    0x2FU      /*!< Service I/O control */
#define SERVICE_FAULT_MEMORY_READ         0x19U      /*!< Service fault memory read */
#define SERIVCE_FAULT_MEMORY_CLEAR        0x14U      /*!< Service fault memory clear */

/* Define PCI request services */
#define PCI_SAVE_CONFIGURATION            0x01U      /*!< PCI value save configuration */

/* Define PCI response's services */
#define PCI_RES_READ_BY_IDENTIFY          0x06U      /*!< PCI response value read by identify */
#define PCI_RES_SAVE_CONFIGURATION        0x01U      /*!< PCI response value save configuration */
#define PCI_RES_ASSIGN_FRAME_ID_RANGE     0x01U      /*!< PCI response value assign frame id range */

/* Identifier user defined */
#define LIN_READ_USR_DEF_MIN              32U       /*!< Min user defined */
#define LIN_READ_USR_DEF_MAX              63U       /*!< Max user defined */

/* Identification */
#define LD_NEGATIVE_RESPONSE              0x53U      /*!< Negative response */
#define LD_POSITIVE_RESPONSE              0x54U      /*!< Positive response */

/* Low level API return values */
#define LIN_LLD_OK                        0x00U     /*!< Return value is OK */
#define LIN_LLD_ERROR                     0xFFU     /*!< Return value is ERROR */




/* *****************************************************************************
 * LOW LEVEL DRIVER
 ******************************************************************************/

/*!
 * @brief Event id
 * Implements : lin_lld_event_id_t_Class
 */
typedef enum
{
    LIN_LLD_PID_OK                  = 0x00U,    /*!< LIN_LLD_PID_OK */
    LIN_LLD_TX_COMPLETED            = 0x01U,    /*!< LIN_LLD_TX_COMPLETED */
    LIN_LLD_RX_COMPLETED            = 0x02U,    /*!< LIN_LLD_RX_COMPLETED */
    LIN_LLD_PID_ERR                 = 0x03U,    /*!< LIN_LLD_PID_ERR */
    LIN_LLD_FRAME_ERR               = 0x04U,    /*!< LIN_LLD_FRAME_ERR */
    LIN_LLD_CHECKSUM_ERR            = 0x05U,    /*!< LIN_LLD_CHECKSUM_ERR */
    LIN_LLD_READBACK_ERR            = 0x06U,    /*!< LIN_LLD_READBACK_ERR */
    LIN_LLD_NODATA_TIMEOUT          = 0x07U,    /*!< No data timeout or received part of data but not completed */
    LIN_LLD_BUS_ACTIVITY_TIMEOUT    = 0x08U,     /*!< LIN_LLD_BUS_ACTIVITY_TIMEOUT */
    LIN_LLD_TX_BIT_ERR              = 0x09U,    /*!< LIN_LLD_TX_BIT_ERR */
    LIN_LLD_SYNC_ERR              = 0x0AU,    /*!< LIN_LLD_SYNC_ERR */
    LIN_LLD_RX_OVERFLOW              = 0x0BU,    /*!< LIN_LLD_RX_OVERFLOW */
    LIN_LLD_TX_TIMEOUT              = 0x0CU,    /*!< LIN_LLD_TX_TIMEOUT */
    LIN_LLD_RX_TIMEOUT             = 0x0DU,    /*!< LIN_LLD_RX_TIMEOUT */
} lin_lld_event_id_t;

/* *****************************************************************************
 * Protocol
 ******************************************************************************/
/*!
 * @brief List of protocols
 * Implements : lin_protocol_handle_t_Class
 */
typedef enum
{
    LIN_PROTOCOL_21     = 0x00U,    /*!< LIN protocol version 2.1, 2.2 */
    LIN_PROTOCOL_J2602  = 0x01U,    /*!< J2602 protocol */
	LIN_PROTOCOL_13     = 0x02U     /*!< LIN protocol version 1.3 */
} lin_protocol_handle_t;

/*!
 * @brief List of diagnostic classes
 * Implements : lin_diagnostic_class_t_Class
 */
typedef enum
{
    LIN_DIAGNOSTIC_CLASS_I      = 0x01U,    /*!< LIN Diagnostic Class 1 */
    LIN_DIAGNOSTIC_CLASS_II     = 0x02U,    /*!< LIN Diagnostic Class 2*/
    LIN_DIAGNOSTIC_CLASS_III    = 0x03U     /*!< LIN Diagnostic Class 3 */
} lin_diagnostic_class_t;

/*!
 * @brief status of LIN bus
 * Implements : lin_word_status_str_t_Class
 */
typedef struct
{
    unsigned int error_in_res                  : 1;        /*!< Error in response */
    unsigned int successful_transfer           : 1;        /*!< Successful transfer */
    unsigned int overrun                       : 1;        /*!< Overrun */
    unsigned int go_to_sleep_flg               : 1;        /*!< Goto sleep */
    unsigned int bus_activity                  : 1;        /*!< Bus activity */
    unsigned int event_trigger_collision_flg   : 1;        /*!< Event trigger collision */
    unsigned int save_config_flg               : 1;        /*!< Save configuration */
    unsigned int reserved                      : 1;        /*!< Dummy */
    unsigned int last_pid                      : 8;        /*!< Last PID */
} lin_word_status_str_t;

/* *****************************************************************************
 * Interfaces
 ******************************************************************************/
/*! @brief Mode of LIN node (master or slave) */
#define    LIN_SLAVE  0    /*!< Slave node */
#define    LIN_MASTER 1    /*!< Master node */

/* *****************************************************************************
 * General
 ******************************************************************************/
typedef union
{
	uint16_t Value;

	struct
	{
		uint16_t Reset						:	1;	// 重置 ------------ 优先级最低
		uint16_t Rx_Overflow_Err 			:	1;	// 接收过载错误
		uint16_t Rx_Sync_Err 				:	1;	// 接收同步段错误
		uint16_t Tx_ReadBack_Err 			:	1;	// 发送时读回值错误
		uint16_t Rx_Check_Sum_Err			:	1;	// 接收校验和错误
		uint16_t Rx_ByteField_Framing_Err	:	1;	// 字节字段帧错误
		uint16_t Tx_Bit_Err					:	1;	// 字节字段帧错误
		uint16_t Tx_Data_Timeout			:	1;	// 发送超时
		uint16_t Rx_Data_Timeout			:	1;	// 接收超时 
		uint16_t Rx_Pid_Check_Err			:	1;	// 接收PID校验错误 -- 优先级最高
		uint16_t Err_Reserved2_7			:	6;	// 预留
		
	}Bit;

}lin_protocol_ResponeErr_Type;


/*!
 * @brief Attributes of LIN node
 * Implements : lin_node_attribute_t_Class
 */
typedef struct
{
    lin_product_id_t        product_id;                 /*!< Product ID */
	lin_protocol_ResponeErr_Type   *ResponeErr_Type; /*!< Frame_Buff_data_ptr */

  
} lin_node_attribute_t;

/* *****************************************************************************
 * Frame
 ******************************************************************************/
/*!
 * @brief Types of frame
 * Implements : lin_frame_type_t_Class
 */
typedef enum
{
    LIN_FRM_UNCD  = 0x00U,  /*!< Unconditional frame */
    LIN_FRM_EVNT  = 0x01U,  /*!< Event triggered frame */
    LIN_FRM_SPRDC = 0x10U,  /*!< Sporadic frame */
    LIN_FRM_DIAG  = 0x11U,   /*!< Diagnostic frame */
    LIN_FRM_PROPRIETARY  = 0x100U   /*!< Proprietary protocol frame */
} lin_frame_type_t;

/*!
 * @brief LIN frame response
 * Implements : lin_frame_response_t_Class
 */
typedef enum
{
    LIN_RES_PUB     = 0x00U,    /*!< Publisher response */
    LIN_RES_SUB     = 0x01U     /*!< Subscriber response */
} lin_frame_response_t;

/*!
 * @brief Informations of associated frame
 * Implements : lin_associate_frame_t_Class
 */
typedef struct
{
    uint8_t num_of_associated_uncond_frames;               /*!< Number of associated unconditional frame ID */
    const uint8_t * associated_uncond_frame_ptr; /*!< Associated unconditional frame ID */
    uint8_t coll_resolv_schd;                              /*!< Collision resolver index in the schedule table, used in event trigger frame case MASTER */
} lin_associate_frame_t;

/*!
 * @brief Frame description structure
 * Implements : lin_frame_t_Class
 */
typedef struct
{
    lin_frame_type_t               frm_type;         /*!< Frame information (unconditional or event triggered..) */
    uint8_t                           frm_len;          /*!< Length of the frame */
    lin_frame_response_t           frm_response;     /*!< Action response when received PID */
		uint16_t                          frm_offset;       /*!< Frame byte offset in frame buffer */
    //uint8_t                          SendRecvEnable;       /*!< Frame byte offset in frame buffer */
} lin_frame_t;

/* *****************************************************************************
 * Schedule table
 ******************************************************************************/
/*!
 * @brief LIN transport layer queue
 * Implements : lin_tl_queue_t_Class
 */

/*!
 * @brief Types of schedule tables
 * Implements : lin_sch_tbl_type_t_Class
 */
typedef enum
{
    LIN_SCH_TBL_NULL        = 0x00U,   /*!< Run nothing */
    LIN_SCH_TBL_NORM        = 0x01U,   /*!< Normal schedule table */
    LIN_SCH_TBL_DIAG        = 0x02U,   /*!< Diagnostic schedule table */
    LIN_SCH_TBL_GO_TO_SLEEP = 0x03U,   /*!< Goto sleep schedule table */
    LIN_SCH_TBL_COLL_RESOLV = 0x04U    /*!< Collision resolving schedule table */
} lin_sch_tbl_type_t;


/* *****************************************************************************
 * Transport Layer / Diagnostic
 ******************************************************************************/
/*!
 * @brief Diagnostic mode
 * Implements : l_diagnostic_mode_t_Class
 */
typedef enum
{
    DIAG_NONE               = 0x00U,    /*!< None */
    DIAG_INTERLEAVE_MODE    = 0x01U,    /*!< Interleave mode */
    DIAG_ONLY_MODE          = 0x02U     /*!< Diagnostic only mode */
} l_diagnostic_mode_t;

/*!
 * @brief Status of the last configuration call for LIN 2.1
 * Implements : lin_service_status_t_Class
 */
typedef enum
{
    LD_SERVICE_BUSY         = 0x00U,    /*!< Service is ongoing */
    LD_REQUEST_FINISHED     = 0x01U,    /*!< The configuration request has been completed */
    LD_SERVICE_IDLE         = 0x02U,    /*!< The configuration request/response combination has been completed */
    LD_SERVICE_ERROR        = 0x03U     /*!< The configuration request or response experienced an error */
} lin_service_status_t;

/*!
 * @brief Status of the last configuration call completed
 * Implements : lin_last_cfg_result_t_Class
 */
typedef enum
{
    LD_SUCCESS              = 0x00U,    /*!< The service was successfully carried out */
    LD_NEGATIVE             = 0x01U,    /*!< The service failed, more information can be found by parsing error_code */
    LD_NO_RESPONSE          = 0x02U,    /*!< No response was received on the request */
    LD_OVERWRITTEN          = 0x03U     /*!< The slave response frame has been overwritten by another operation */
} lin_last_cfg_result_t;

/*!
 * @brief Transport layer event IDs
 * Implements : lin_tl_event_id_t_Class
 */
typedef enum
{
    TL_MAKE_RES_DATA           = 0x00U, /*!< Make master request data */
    TL_SLAVE_GET_ACTION        = 0x01U, /*!< Get slave action */
    TL_TX_COMPLETED            = 0x02U, /*!< Transmit completed */
    TL_RX_COMPLETED            = 0x03U, /*!< Receive completed */
    TL_ERROR                   = 0x04U, /*!< Transport error */
    TL_TIMEOUT_SERVICE         = 0x05U, /*!< Transmit timeout */
    TL_HANDLER_INTERLEAVE_MODE = 0x06U, /*!< Interleave mode */
    TL_RECEIVE_MESSAGE         = 0x07U  /*!< Return data for ld_receive_message function */
} lin_tl_event_id_t;

/*!
 * @brief Transport layer event IDs
 * Implements : lin_tl_callback_return_t_Class
 */
typedef enum
{
    TL_ACTION_NONE      = 0x00U,     /*!< Default return value of call back function */
    TL_ACTION_ID_IGNORE = 0x01U      /*!< Ignore this ID */
} lin_tl_callback_return_t;

extern lin_tl_callback_return_t lin_tl_callback_handler(l_ifc_handle iii,
                                                        lin_tl_event_id_t tl_event_id,
                                                        uint8_t id);

#define LIN_TL_CALLBACK_HANDLER(iii, tl_event_id, id) lin_tl_callback_handler((iii), (tl_event_id), (id))
/* ---------------------- Transport layer multi frames ---------------------- */
/*!
 * @brief Status of queue
 * Implements : ld_queue_status_t_Class
 */
typedef enum
{
    LD_NO_DATA              = 0x00U,    /*!< Rx Queue is empty, has no data */
    LD_DATA_AVAILABLE       = 0x01U,    /*!< Data in queue is available */
    LD_RECEIVE_ERROR        = 0x02U,    /*!< Receive data is error for LIN21 and above*/
    LD_QUEUE_FULL           = 0x03U,    /*!< The queue is full */
    LD_QUEUE_AVAILABLE      = 0x04U,    /*!< Queue is available for insert data for LIN21 and above*/
    LD_QUEUE_EMPTY          = 0x05U,    /*!< Tx Queue is empty */
    LD_TRANSMIT_ERROR       = 0x06U,    /*!< Error while transmitting for LIN21 and above */
    LD_TRANSFER_ERROR       = 0x07U     /*!< Error while transmitting/receiving for LIN20 and J2602 */
} ld_queue_status_t;

/*!
 * @brief Status of LIN message
 * Implements : lin_message_status_t_Class
 */
typedef enum
{
    LD_NO_MSG               = 0x00U,    /*!< No message */
    LD_IN_PROGRESS          = 0x01U,    /*!< In progress */
    LD_COMPLETED            = 0x02U,    /*!< Completed */
    LD_FAILED               = 0x03U,    /*!< Failed */
    LD_N_AS_TIMEOUT         = 0x04U,    /*!< N_As timeout */
    LD_N_CR_TIMEOUT         = 0x05U,    /*!< N_Cr timeout */
    LD_WRONG_SN             = 0x06U     /*!< Wrong sequence number */
} lin_message_status_t;

/*!
 * @brief LIN diagnostic state
 * Implements : lin_diagnostic_state_t_Class
 */
typedef enum
{
    LD_DIAG_IDLE                = 0x01U,    /*!< IDLE */
    LD_DIAG_TX_PHY              = 0x02U,    /*!< Diagnostic transmit physical */
    LD_DIAG_TX_FUNCTIONAL       = 0x03U,    /*!< Diagnostic transmit active */
    LD_DIAG_TX_INTERLEAVED      = 0x04U,    /*!< Diagnostic transmit in interleave mode */
    LD_DIAG_RX_PHY              = 0x05U,    /*!< Diagnostic receive in physical */
    LD_DIAG_RX_FUNCTIONAL       = 0x06U,    /*!< Diagnostic receive functional request */
    LD_DIAG_RX_INTERLEAVED      = 0x07U     /*!< Diagnostic receive in interleave mode */
} lin_diagnostic_state_t;

/*!
 * @brief Types of message timeout
 * Implements : lin_message_timeout_type_t_Class
 */
typedef enum
{
    LD_NO_CHECK_TIMEOUT      = 0x00U,   /*!< No check timeout */
    LD_CHECK_N_AS_TIMEOUT    = 0x01U,   /*!< check N_As timeout */
    LD_CHECK_N_CR_TIMEOUT    = 0x02U    /*!< check N_Cr timeout */
} lin_message_timeout_type_t;



#define INTERLEAVE_MAX_TIMEOUT (uint16_t)(1000000U/TIME_OUT_UNIT_US)      /*!< Slave node interleaved diagnostic response timeout */

/*!
 * @brief State of diagnostic interleaved mode
 * Implements : diag_interleaved_state_t_Class
 */
typedef enum
{
    DIAG_NOT_START          = 0x00U,    /*!< Not into slave response schedule with interleaved mode */
    DIAG_NO_RESPONSE        = 0x01U,    /*!< Master send 0x3D but slave does not response */
    DIAG_RESPONSE           = 0x02U     /*!< Response receive */
} diag_interleaved_state_t;



/* *****************************************************************************
 * Configuration
 ******************************************************************************/
/*!
 * @brief Configuration structure
 * Implements : lin_protocol_user_config_t_Class
 */
typedef struct
{
    lin_protocol_handle_t       protocol_version;   /*!< Protocol version */
    lin_protocol_handle_t       language_version;   /*!< Language version */
    lin_diagnostic_class_t      diagnostic_class;   /*!< Diagnostic class */
    bool                        function;           /*!< Function LIN_MASTER or LIN_SLAVE_) */
    /* Protocol */
    uint8_t                        number_of_schedule_Tbl;      /*!< Number of frame except diagnostic frames */
    uint8_t                        frame_start;                        /*!< Start index of frame list */
    uint16_t                       max_idle_timeout_cnt;      /*!< Max Idle timeout counter */
    l_ifc_slave_handle          slave_ifc_handle;          /*!< Interface handler of slave node */
    lin_user_config_t           *lin_user_config_ptr;      /*!< Pointer to LIN driver user configuration structure */
	uint8_t 						*list_schedule_tbl_En_ptr;
} lin_protocol_user_config_t;
typedef struct
{
	uint8_t                         number_of_configurable_frames;      /*!< Number of frame except diagnostic frames */
	uint16_t                        number_of_configurable_buf;      /*!< Number of frame except diagnostic frames */	
	uint8_t 						*list_Node_tbl_En_ptr;	
	const lin_frame_t               *frame_tbl_ptr;     
	const uint16_t                  *list_identifiers_ROM_ptr; /*!< Configuration in ROM */
	uint8_t                         *list_identifiers_RAM_ptr; /*!< Configuration in RAM */
	volatile uint8_t                *Frame_Buff_data_ptr; /*!< Frame_Buff_data_ptr */

} lin_protocol_Ldf_config_t;



/*!
 * @brief LIN protocol status structure
 * Implements : lin_protocol_state_t_Class
 */
typedef struct
{
    /* LIN data pointer */
    uint16_t                  baud_rate;             /*!< Adjusted baud rate */
    uint8_t                   *response_buffer_ptr;  /*!< Response buffer */
    uint8_t                   response_length;       /*!< Response length  */
    uint8_t                   successful_transfer;   /*!< Transfer flag */
    uint8_t                   error_in_response;     /*!< Error response */
    BOOL                 go_to_sleep_flg;       /*!< Go to sleep flag */
    uint8_t                   current_id;            /*!< Current PID */
    uint8_t                   last_pid;              /*!< Last PID */
    uint8_t                   num_of_processed_frame;/*!< Number of processed frames */
    uint8_t                   overrun_flg;           /*!< overrun flag */
    lin_word_status_str_t  word_status;           /*!< Word status */
    uint8_t                   next_transmit_tick;    /*!< Used to count the next transmit tick */
    BOOL                 save_config_flg;       /*!< Set when save configuration request has been received */
    l_diagnostic_mode_t    diagnostic_mode;       /*!< Diagnostic mode */
    uint16_t                  frame_timeout_cnt;     /*!< Frame timeout counter for monitoring if timeout occurs during data transferring */
    uint16_t                  idle_timeout_cnt;      /*!< Idle timeout counter */
    BOOL                 transmit_error_resp_sig_flg; /*!< Flag indicates that the error response signal is going to be sent */
} lin_protocol_state_t;
/* End of data definition */



/* *****************************************************************************
 * Extern variables
 ******************************************************************************/
#if (SUPPORT_SLAVE_MODE == 1U)
extern const lin_node_attribute_t           g_lin_node_attribute_array[LIN_NUM_OF_SLAVE_IFCS];
#endif /* End (SUPPORT_SLAVE_MODE == 1U) */


extern const lin_protocol_user_config_t     g_lin_protocol_user_cfg_array[LIN_NUM_OF_IFCS];
extern const lin_protocol_Ldf_config_t g_lin_protocol_ldf_cfg_array[LIN_NUM_OF_SCHEDULE_TBL];

extern lin_protocol_state_t                 g_lin_protocol_state_array[LIN_NUM_OF_IFCS];


extern volatile uint8_t    g_lin_Diag_Tx_data_buffer[LIN_DIAG_TX_BUF_SIZE];
extern volatile uint8_t    g_lin_Diag_Rx_data_buffer[LIN_DIAG_TX_BUF_SIZE];
extern volatile uint8_t    g_lin_Diag_Tx_data_Len;

extern volatile uint8_t    g_lin_Proprietary_Tx_data_buffer[LIN_PROPRIETARY_TX_BUF_SIZE];
extern volatile uint8_t    g_lin_Proprietary_Rx_data_buffer[LIN_PROPRIETARY_RX_BUF_SIZE];


extern const uint32_t                          g_lin_virtual_ifc[LIN_NUM_OF_IFCS];
extern const l_ifc_handle                   g_lin_hardware_ifc[HARDWARE_INSTANCE_COUNT];
extern volatile uint8_t                        g_buffer_backup_data[8];


/* *****************************************************************************
 * Static functions
 ******************************************************************************/
/*!
 * @brief Computes maximum header timeout
 *
 * Theader_Maximum = 1.4 * THeader_Nominal, THeader_Nominal = 34 * TBit,
 * (13 nominal bits of break;   1 nominal bit of break delimiter; 10 bits for SYNC and 10 bits of PID)
 * TIME_OUT_UNIT_US is in micro second
 *
 * @param[in] baudRate LIN network baud rate
 * @return    maximum timeout for the selected baud rate
 *
 * Implements : lin_calc_max_header_timeout_cnt_Activity
 */
static inline uint16_t lin_calc_max_header_timeout_cnt(uint32_t baudRate)
{
    return (uint16_t)((14U * 34U * 100000U / (TIME_OUT_UNIT_US * baudRate)) + 1U);
}

/*!
 * @brief Computes the maximum response timeout
 *
 * TResponse_Maximum = 1.4 * TResponse_Nominal, TResponse_Nominal = 10 * (NData+ 1) * TBit
 *
 * @param[in] baudRate LIN network baud rate
 * @param[in] size     frame size in bytes
 * @return maximum response timeout for the given baud rate and frame size
 *
 * Implements : lin_calc_max_res_timeout_cnt_Activity
 */
static inline uint16_t lin_calc_max_res_timeout_cnt(uint32_t baudRate,
                                                 uint8_t size)
{
    uint16_t a = (uint16_t)(14U * (1U + (uint16_t)size));

    return (uint16_t)((a * 1000000U / (TIME_OUT_UNIT_US * baudRate)) + 1U);
}

/* *****************************************************************************
 * Global functions
 ******************************************************************************/
/*!
 * @brief Makes or checks parity bits. If action is checking parity, the function
 * returns ID value if parity bits are correct or 0xFF if parity bits are incorrect. If action
 * is making parity bits, then from input value of ID, the function returns PID.
 *
 * @param pid PID byte in case of checking parity bits or ID byte in case of making parity bits.
 * @param typeAction TRUE for Checking parity bits, FALSE for making parity bits
 * @return 0xFF if parity bits are incorrect, ID in case of checking parity bits and
 * they are correct. Function returns PID in case of making parity bits.
 */
uint8_t lin_process_parity(uint8_t pid,
                        uint8_t typeAction);

/*!
 * @brief Callback handler for low level events
 *
 * This callback handler is being called from the LIN driver callback
 *
 * @param[in] iii LIN interface that is being handled
 * @param[in] event_id  Low level event id #lin_lld_event_id_t
 * @param[in] id Current protected identifier under processing by driver
 */
extern void lin_pid_resp_callback_handler(l_ifc_handle iii,
                                          const lin_lld_event_id_t event_id,
                                          uint8_t id);

/*!
 * @brief CALLBACK_HANDLER.
 *
 * @note call lin_pid_resp_callback_handler() function in MASTER mode
 */
#define CALLBACK_HANDLER(iii, event_id, id) lin_pid_resp_callback_handler((iii), (event_id), (id))







/*!
 * @brief This function initializes a LIN hardware instance for operation.
 * This function will initialize the run-time state structure to keep track of
 * the on-going transfers, initialize the module to user defined settings and
 * default settings, configure the IRQ state structure and enable the module-level
 * interrupt to the core, and enable the LIN hardware module transmitter and receiver.
 *
 * @param[in] iii LIN interface that is being handled
 * @return zero if the initialization was successful and non-zero if failed
 */
BOOL lin_lld_init(l_ifc_handle iii);

void lin_lld_Wakeup(l_ifc_handle iii);


/*!
 * @brief This function disconnect the node from the cluster and
 *  free all hardware used
 *
 * @param[in] iii LIN interface that is being handled
 * @return Zero for success
 * @return void
 */
void lin_lld_deinit(l_ifc_handle iii);



/*!
 * @brief This function gets current state of an interface
 *
 * @param[in] iii LIN interface that is being handled
 * @return current LIN node state
 */
lin_node_state_t lin_lld_get_state(l_ifc_handle iii);


/*!
 * @brief This function send a wakeup signal
 *
 * @param[in] iii LIN interface that is being handled
 * @return Zero for success
 * @return Non-zero for error
 */
uint8_t lin_lld_tx_wake_up(l_ifc_handle iii);

/*!
 * @brief This function terminates an on-going data transmission/reception.
 *
 * @param[in] iii LIN interface that is being handled
 * @return Zero for success
 * @return Non-zero for error
 */
uint8_t lin_lld_ignore_response(l_ifc_handle iii);

/*!
 * @brief Let the low level driver go to low power mode
 *
 * @param[in] iii LIN interface that is being handled
 * @return Zero for success
 * @return Non-zero for error
 */
uint8_t lin_lld_set_low_power_mode(l_ifc_handle iii);

/*!
 * @brief This function sends frame data that is contained in LIN_lld_response_buffer[iii].
 *
 * This function will send the first data byte in the buffer and then return.
 * Next data bytes will be sent in the interrupt handler of LIN interface.
 * This function returns zero if sending of first data byte was successful.
 * @param[in] iii LIN interface that is being handled
 * @param[in] response_length Length of response
 * @return Zero for success
 * @return Non-zero for error
 */
uint8_t lin_lld_set_response(l_ifc_handle iii,
                          uint8_t response_length);

/*!
 * @brief This function receives frame data into the LIN_lld_response_buffer[iii] buffer.
 *
 * This function will prepare LIN interface to receive data and then return.
 * Data bytes will be received to the buffer in the interrupt handler of LIN
 * interface.
 * This function returns zero if preparation of receiving data was successful.
 * @param[in] iii LIN interface that is being handled
 * @param[in] response_length Length of response
 * @return Zero for success
 * @return Non-zero for error
 */
uint8_t lin_lld_rx_response(l_ifc_handle iii,
                         uint8_t response_length);

/*!
 * @brief Callback function for Timer Interrupt Handler
 * In timer IRQ handler, call this function. Used to check if frame timeout has occurred during
 * frame data transmission and reception, to check for N_As and N_Cr timeout for LIN 2.1 and
 * above. This function also check if there is no LIN bus communication (no headers and no frame
 * data transferring) for Idle timeout (s), then put LIN node to Sleep mode. Users may initialize
 * a timer (for example FTM)with period of Timeout unit (default: 500 micro seconds) to call
 * lin_lld_timeout_service().
 * For an interface iii, Idle timeout (s) = max_idle_timeout_cnt * Timeout unit (us)
 * frame timeout (us) = frame_timeout_cnt * Timeout unit (us)
 * N_As timeout (us) = N_As_timeout * Timeout unit (us)
 * N_Cr timeout (us) = N_Cr_timeout * Timeout unit (us)
 * @param[in] iii LIN interface that is being handled
 * @return void
 */
void lin_lld_timeout_service(l_ifc_handle iii);
extern lin_protocol_ResponeErr_Type* ld_Get_lin_ResponeErr_Status(void);
#endif /* LIN_H */

/*! @} */

/* ****************************************************************************/
/* EOF */
/* ****************************************************************************/
