/******************************************************************************
 *                        Shanghai ChipON Micro-Electronic Co.,Ltd
 ******************************************************************************
 *  @File Name       : Stop0_Wakeup_Vector.c
 *  @Syntax          : GNU99
 *  @Author          : ChipON AE/FAE Group
 *  @Date            : 2025-08-15
 *  @Version         : V1.0.0_SF
 *  @Description     : This document describes the C language document template.
 ******************************************************************************
 *  Copyright (C) by Shanghai ChipON Micro-Electronic Co.,Ltd
 *  All rights reserved.
 *
 *  This software is copyright protected and proprietary to
 *  Shanghai ChipON Micro-Electronic Co.,Ltd.
 ******************************************************************************
 *                        REVISION HISTORY
 ******************************************************************************
 *  |Date        |Version  |Author       |Description
 ******************************************************************************
 *  |2025-08-15  |V1.0     |Zhou Jie     |New create
 *****************************************************************************/

/******************************************************************************
 **                      QAC Warnings
 ******************************************************************************/
/* PRQA S 0303,0306 EOF #KQR100303 */
/* PRQA S 3415 EOF #KQR003415 */
/* PRQA S 1006,3006 EOF #KQR101006 */
/* PRQA S 0602,0603 EOF #KQR100602 */
/* PRQA S 0674 EOF #KQR100674 */

/* PRQA S 5209 EOF #Variable from IDE or LD */
/* PRQA S 1533 EOF #Enhance scalability */
/* PRQA S 0616 EOF #KQR000616 */
/* PRQA S 2071 EOF #KQR002071 */
/* PRQA S 2201 EOF #KQR002201 */
/* PRQA S 3384 EOF #KQR003384 */
/******************************************************************************
 *                      Include Files
 ******************************************************************************/
#include "kf32a158sf_drv_gpio.h"

#include "kf32a158sf_drv_gptimer.h"
#include "kf32a158sf_drv_rst.h"
#include "kf32a158sf_drv_intr.h"
#include "kf32a158sf_drv_osc.h"
#include "kf32a158sf_drv_pm.h"
#include "kf32a158sf_drv_sysctl.h"
#include "kf32a158sf_drv_pclk.h"

typedef void (*interruptVector)(void);

struct vectorTableType
{

    int            *value;       // auto variable by tool ,value is default sp
    interruptVector Reset_Enter; // Enter Function,design lead function and run to main

    interruptVector NMI_Enter;
    interruptVector HardFault_Enter;
    interruptVector Rev4_Enter;
    interruptVector StackFault_Enter;
    interruptVector AriFault_Enter;
    interruptVector Intended_Rev; // create characteristic by linker,code write 0 here

    interruptVector interrupt[120]; // other
};
/* PRQA S 1752 1 #KQR001752 */
extern int __initial_sp;
/* PRQA S 1753 1 #Generated by IDE */
extern void startup(void);
/* PRQA S 1513 2 #KQR001513 */
/* PRQA S 1510 1 #KQR100022 */
struct vectorTableType __Stop0_Wakeup_Vector __attribute__((section(".indata")));

/* PRQA S 1753 3 #Generated by IDE */
void __attribute__((interrupt)) __attribute__((section(".indata"))) __Stop0_Wakeup_exception(void);
void __attribute__((interrupt)) __attribute__((section(".indata"))) __Stop0_Wakeup_T0_exception(void);
void __attribute__((interrupt)) __attribute__((section(".indata"))) __Stop0_Wakeup_EINT31TO20_exception(void);
void __attribute__((interrupt)) __attribute__((section(".indata"))) __Stop0_Wakeup_WKP0TO5_exception(void);
/* PRQA S 1510 1 #KQR100022 */
struct vectorTableType __Stop0_Wakeup_Vector __attribute__((section(".indata"))) = {
  &__initial_sp,
  &startup,
  &__Stop0_Wakeup_exception, // V2
  &__Stop0_Wakeup_exception, // V3
  &__Stop0_Wakeup_exception, // V4
  &__Stop0_Wakeup_exception, // V5
  &__Stop0_Wakeup_exception, // V6
  NULL,
  {
    &__Stop0_Wakeup_exception,            // V8
    &__Stop0_Wakeup_exception,            // V9
    &__Stop0_Wakeup_exception,            // V10
    &__Stop0_Wakeup_exception,            // V11
    &__Stop0_Wakeup_exception,            // V12
    &__Stop0_Wakeup_exception,            // V13
    &__Stop0_Wakeup_exception,            // V14
    &__Stop0_Wakeup_exception,            // V15
    &__Stop0_Wakeup_exception,            // V16
    &__Stop0_Wakeup_exception,            // V17
    &__Stop0_Wakeup_exception,            // V18
    &__Stop0_Wakeup_exception,            // V19
    &__Stop0_Wakeup_exception,            // V20
    &__Stop0_Wakeup_exception,            // V21
    &__Stop0_Wakeup_exception,            // V22
    &__Stop0_Wakeup_exception,            // V23
    &__Stop0_Wakeup_exception,            // V24
    &__Stop0_Wakeup_exception,            // V25
    &__Stop0_Wakeup_exception,            // V26
    &__Stop0_Wakeup_exception,            // V27
    &__Stop0_Wakeup_exception,            // V28
    &__Stop0_Wakeup_exception,            // V29
    &__Stop0_Wakeup_exception,            // V30
    &__Stop0_Wakeup_exception,            // V31
    &__Stop0_Wakeup_exception,            // V32
    &__Stop0_Wakeup_exception,            // V33
    &__Stop0_Wakeup_exception,            // V34
    &__Stop0_Wakeup_exception,            // V35
    &__Stop0_Wakeup_exception,            // V36
    &__Stop0_Wakeup_exception,            // V37
    &__Stop0_Wakeup_exception,            // V38
    &__Stop0_Wakeup_exception,            // V39
    &__Stop0_Wakeup_exception,            // V40
    &__Stop0_Wakeup_T0_exception,         // V41
    &__Stop0_Wakeup_exception,            // V42
    &__Stop0_Wakeup_exception,            // V43
    &__Stop0_Wakeup_exception,            // V44
    &__Stop0_Wakeup_exception,            // V45
    &__Stop0_Wakeup_exception,            // V46
    &__Stop0_Wakeup_exception,            // V47
    &__Stop0_Wakeup_exception,            // V48
    &__Stop0_Wakeup_exception,            // V49
    &__Stop0_Wakeup_exception,            // V50
    &__Stop0_Wakeup_exception,            // V51
    &__Stop0_Wakeup_exception,            // V52
    &__Stop0_Wakeup_exception,            // V53
    &__Stop0_Wakeup_EINT31TO20_exception, // V54
    &__Stop0_Wakeup_exception,            // V55
    &__Stop0_Wakeup_exception,            // V56
    &__Stop0_Wakeup_exception,            // V57
    &__Stop0_Wakeup_exception,            // V58
    &__Stop0_Wakeup_exception,            // V59
    &__Stop0_Wakeup_exception,            // V60
    &__Stop0_Wakeup_exception,            // V61
    &__Stop0_Wakeup_exception,            // V62
    &__Stop0_Wakeup_exception,            // V63
    &__Stop0_Wakeup_exception,            // V64
    &__Stop0_Wakeup_exception,            // V65
    &__Stop0_Wakeup_exception,            // V66
    &__Stop0_Wakeup_exception,            // V67
    &__Stop0_Wakeup_exception,            // V68
    &__Stop0_Wakeup_exception,            // V69
    &__Stop0_Wakeup_exception,            // V70
    &__Stop0_Wakeup_exception,            // V71
    &__Stop0_Wakeup_exception,            // V72
    &__Stop0_Wakeup_WKP0TO5_exception,    // V73
    &__Stop0_Wakeup_exception,            // V74
    &__Stop0_Wakeup_exception,            // V75
    &__Stop0_Wakeup_exception,            // V76
    &__Stop0_Wakeup_exception,            // V77
    &__Stop0_Wakeup_exception,            // V78
    &__Stop0_Wakeup_exception,            // V79
    &__Stop0_Wakeup_exception,            // V80
    &__Stop0_Wakeup_exception,            // V81
    &__Stop0_Wakeup_exception,            // V82
    &__Stop0_Wakeup_exception,            // V83
    &__Stop0_Wakeup_exception,            // V84
    &__Stop0_Wakeup_exception,            // V85
    &__Stop0_Wakeup_exception,            // V86
    &__Stop0_Wakeup_exception,            // V87
    &__Stop0_Wakeup_exception,            // V88
    &__Stop0_Wakeup_exception,            // V89
    &__Stop0_Wakeup_exception,            // V90
    &__Stop0_Wakeup_exception,            // V91
    &__Stop0_Wakeup_exception,            // V92
    &__Stop0_Wakeup_exception,            // V93
    &__Stop0_Wakeup_exception,            // V94
    &__Stop0_Wakeup_exception,            // V95
    &__Stop0_Wakeup_exception,            // V96
    &__Stop0_Wakeup_exception,            // V97
    &__Stop0_Wakeup_exception,            // V98
    &__Stop0_Wakeup_exception,            // V99
    &__Stop0_Wakeup_exception,            // V100
    &__Stop0_Wakeup_exception,            // V101
    &__Stop0_Wakeup_exception,            // V102
    &__Stop0_Wakeup_exception,            // V103
    &__Stop0_Wakeup_exception,            // V104
    &__Stop0_Wakeup_exception,            // V105
    &__Stop0_Wakeup_exception,            // V106
    &__Stop0_Wakeup_exception,            // V107
    &__Stop0_Wakeup_exception,            // V108
    &__Stop0_Wakeup_exception,            // V109
    &__Stop0_Wakeup_exception,            // V110
    &__Stop0_Wakeup_exception,            // V111
    &__Stop0_Wakeup_exception,            // V112
    &__Stop0_Wakeup_exception,            // V113
    &__Stop0_Wakeup_exception,            // V114
    &__Stop0_Wakeup_exception,            // V115
    &__Stop0_Wakeup_exception,            // V116
    &__Stop0_Wakeup_exception,            // V117
    &__Stop0_Wakeup_exception,            // V118
    &__Stop0_Wakeup_exception,            // V119
    &__Stop0_Wakeup_exception,            // V120
    &__Stop0_Wakeup_exception,            // V121
    &__Stop0_Wakeup_exception,            // V122
    &__Stop0_Wakeup_exception,            // V123
    &__Stop0_Wakeup_exception,            // V124
    &__Stop0_Wakeup_exception,            // V125
    &__Stop0_Wakeup_exception,            // V126
    &__Stop0_Wakeup_exception             // V127
  }

};

//*****************************************************************************************
//                              WKP5TO0 Interrupt Course in STOP0 Mode
//*****************************************************************************************
/* PRQA S 0602,2888 1 #KQR100017 */
void __attribute__((interrupt)) __attribute__((section(".indata"))) __Stop0_Wakeup_WKP0TO5_exception(void)
{
    uint32_t tmpBkpReadWriteEn;

    /* Disable WKUP Interrupt. */
    INTR_PTR->EIE2.bits.WKPIE = 0U;
    /** Record and enable PMWREN */
    tmpBkpReadWriteEn         = OSC_PTR->CTL0.bits.PMWREN;
    OSC_PTR->CTL0.bits.PMWREN = 1U;

    /** Clear PMCIF */
    PM_PTR->STAC.bits.PMCIC = 1U;
    NOP();
    NOP();
    NOP();
    NOP();
    PM_PTR->STAC.bits.PMCIC = 0U;

    /** Recover PMWREN */
    OSC_PTR->CTL0.bits.PMWREN = tmpBkpReadWriteEn;
}

//*****************************************************************************************
//                              EINT31TO20 Interrupt Course in STOP0 Mode
//*****************************************************************************************
/* PRQA S 0627,3331 1 #KQR000627 */
void __attribute__((interrupt)) __attribute__((section(".indata"))) __Stop0_Wakeup_EINT31TO20_exception(void)
{
    volatile uint32_t wait_flag = 0x0U;
    uint32_t          tmpBkpReadWriteEn;

    /** Record and enable PMWREN */
    tmpBkpReadWriteEn         = OSC_PTR->CTL0.bits.PMWREN;
    OSC_PTR->CTL0.bits.PMWREN = 1U;

    if ((INTR_PTR->EINTF.reg & ((uint32_t)1U << (uint32_t)INTR_EXTI_INDEX_21)) > 0U)
    {
        PM_PTR->STAC.bits.PMCIC = 1U;
        INTR_PTR->EINTF.reg &= ~((uint32_t)1U << (uint32_t)INTR_EXTI_INDEX_21);

        uint32_t stopErrorBit = PM_PTR->STA1.bits.STOPERROR;
        uint32_t pmcErrorBit  = PM_PTR->STA1.bits.PMCERROR;

        while (((stopErrorBit == 1U) || (pmcErrorBit == 1U)) && (wait_flag != 0xFFFFU))
        {
            stopErrorBit = PM_PTR->STA1.bits.STOPERROR;
            pmcErrorBit  = PM_PTR->STA1.bits.PMCERROR;
            wait_flag += 1U;
        }
        PM_PTR->STAC.bits.PMCIC = 0U;
    }
    else
    { /**Empty */
    }

    /** Recover PMWREN */
    OSC_PTR->CTL0.bits.PMWREN = tmpBkpReadWriteEn;
}

//*****************************************************************************************
//                              T0 Interrupt Course in STOP0 Mode
//*****************************************************************************************
/* PRQA S 0627,3331 1 #KQR000627 */
void __attribute__((interrupt)) __attribute__((section(".indata"))) __Stop0_Wakeup_T0_exception(void)
{
    volatile uint32_t wait_flag = 0x0U;
    T0_PTR->CCP_SRIC.bits.TXIC  = 1U;

    while ((T0_PTR->CTL1.bits.TXIF == 1U) && (wait_flag != 0xFFFFU))
    {
        wait_flag += 1U;
    }
    T0_PTR->CCP_SRIC.bits.TXIC = 0U;
}

//*****************************************************************************************
//                              Default Interrupt Course in STOP0 Mode
//*****************************************************************************************
/* PRQA S 0627,3331 1 #KQR000627 */
void __attribute__((interrupt)) __attribute__((section(".indata"))) __Stop0_Wakeup_exception(void)
{
    /*For undefined interrupts*/
    asm volatile("RESET");
}
