/******************************************************************************
 *                        Shanghai ChipON Micro-Electronic Co.,Ltd
 ******************************************************************************
 *  @File Name        : kflog.h
 *  @Date             : 2025-07-25
 *  @Version          : {{VersionDate}}
 *  @Description     : This document describes the C language document template.
 ******************************************************************************
 *  Copyright (C) by Shanghai ChipON Micro-Electronic Co.,Ltd
 *  All rights reserved.
 *
 *  This software is copyright protected and proprietary to
 *  Shanghai ChipON Micro-Electronic Co.,Ltd.
 ******************************************************************************
 *                        REVISION HISTORY
 ******************************************************************************
 *  |Date        |Version  |Author       |Description
 ******************************************************************************
 *  |2025-07-25  |V1.0     |Zhou Jie     |New creat
 *****************************************************************************/
#ifndef KF_PRINTF_H
#define KF_PRINTF_H

#ifdef __cplusplus
extern "C" {
#endif

/******************************************************************************
 **                        MISRA-C Rules Violations
 ******************************************************************************/

/******************************************************************************
 **                        QAC Warnings
 ******************************************************************************/

/******************************************************************************
 **                        Include Files
 ******************************************************************************/
#include <stdint.h>
/******************************************************************************
 **                        File Version Check
 ******************************************************************************/

/******************************************************************************
 **                        Macro  Definitions
 ******************************************************************************/
#ifdef KF_INTERNAL_PRINT
/**
 * @brief log level
 */
#ifndef KF_LOG_LEVEL_H
#define KF_LOG_LEVEL 0U
#endif

#define KF_LOG_DEBUG (1UL << 0U)
#define KF_LOG_INFO  (1UL << 1U)
#define KF_LOG_WARN  (1UL << 2U)
#define KF_LOG_ERROR (1UL << 3U)

/**
 * @brief The properties printed when the log module is registered
 */
#define KF_LOG_OPT_FUNC ((uint32_t)(1UL << 0U))
#define KF_LOG_OPT_LINE ((uint32_t)(1UL << 1U))
#define KF_LOG_OPT_FILE ((uint32_t)(1UL << 2U))
#define KF_LOG_OPT_TICK ((uint32_t)(1UL << 3U))

/**
 * @brief Registering the Log module
 */
#define KF_REF_LOG(TAG)      extern Log_PrintfType log_##TAG##_module;
#define KF_REG_LOG(TAG, OPT) Log_PrintfType log_##TAG##_module = {.name = #TAG, .opt = (OPT)};

/**
 * @brief Log output, including debugging, information, alarm, and error, is
 * generated by calling different interfaces
 */

#if (KF_LOG_DEBUG > KF_LOG_LEVEL)
#define KFLOG_D(TAG, MSG, ...)                                                                                         \
    kfLog_Printf((Log_PrintfType *)&log_##TAG##_module, __func__, __LINE__, __FILE__, MSG, ##__VA_ARGS__)
#else
#define KFLOG_D(TAG, MSG, ...)
#endif

#if (KF_LOG_INFO > KF_LOG_LEVEL)
#define KFLOG_I(TAG, MSG, ...)                                                                                         \
    kfLog_Printf((Log_PrintfType *)&log_##TAG##_module, __func__, __LINE__, __FILE__, MSG, ##__VA_ARGS__)
#else
#define KFLOG_I(TAG, MSG, ...)
#endif

#if (KF_LOG_WARN > KF_LOG_LEVEL)
#define KFLOG_W(TAG, MSG, ...)                                                                                         \
    kfLog_Printf((Log_PrintfType *)&log_##TAG##_module, __func__, __LINE__, __FILE__, MSG, ##__VA_ARGS__)
#else
#define KFLOG_W(TAG, MSG, ...)
#endif

#if (KF_LOG_ERROR > KF_LOG_LEVEL)
#define KFLOG_E(TAG, MSG, ...)                                                                                         \
    kfLog_Printf((Log_PrintfType *)&log_##TAG##_module, __func__, __LINE__, __FILE__, MSG, ##__VA_ARGS__)
#else
#define KFLOG_E(TAG, MSG, ...)
#endif

/**
 * @brief Pure output (pure), without the registration module header
 *
 * @attention The print length cannot exceed 256 bytes.
 */
#define kf_printf(MSG, ...) kfLog_Printf(NULL, __func__, __LINE__, __FILE__, MSG, ##__VA_ARGS__)
/******************************************************************************
 **                        Typedef  Definitions
 ******************************************************************************/
/* PRQA S 3630 ++ */
/**
 * @brief  Log Output module information
 */
typedef struct
{
    /** @brief Module Name  */
    char *name;
    /** @brief Information Properties */
    uint32_t opt;
} Log_PrintfType;
/* PRQA S 3630 -- */

/******************************************************************************
 **                        Export Variables
 ******************************************************************************/

/******************************************************************************
 **                        Export Functions
 ******************************************************************************/
/**
 * @brief send data
 * @param pSendData-send data point
 * SendLen-send data length
 * @retval None
 */
extern void kfLog_UartSend(const uint8_t *pSendData, uint16_t SendLen);

/**
 * @brief Log information output
 * @param plog_module-Information about the registered module
 * LogLevel-Print level
 * pfun-function name
 * line-line num
 * pfile-The file path
 * format,...-varargs
 * @retval None
 */
extern void kfLog_Printf(const Log_PrintfType *const plog_module, const char *pfun, uint32_t line, const char *pfile,
                         const char *format, ...);

/**
 * @brief Log output initialization
 * 1.The default value is UART0. If you need to change the value, change the
 * KFLOG_UART
 * 2.The default baud rate is 230400
 * 3.8bits Data , 1 start bit, 1 stop bit, no flow control, parity none
 * @param None
 * @retval None
 */
extern void kfLog_Init(void);
#else
#define KF_REF_LOG(TAG)
#define KF_REG_LOG(TAG, OPT)
#define KFLOG_D(TAG, MSG, ...)
#define KFLOG_I(TAG, MSG, ...)
#define KFLOG_W(TAG, MSG, ...)
#define KFLOG_E(TAG, MSG, ...)
#define kf_printf(MSG, ...)
#define kfLog_Init()
#define kfLog_UartSend(pSendData, SendLen)
#endif

#ifdef __cplusplus
}
#endif

#endif
/* EOF */
