/**************************************************************************************************/

/*  ###################################################################
**     This component module is generated by Lin_Geny. Do not modify it.
**
**     @file      Privatelin_cfg.h
**
**     @date      2025-01-09 15:41:07 PM
**
**     @brief     Lin configuration file
**
**     @version   1.00.05
**
**     @Toolversion   LIN Geny V1.10
**
**     @Ldf1FileName   MX11_LZCU_LIN5_240528.ldf
**
**     @Ldf2FileName
**
**     @Ldf3FileName
**
**     @Ldf4FileName   
**
**     Copyright : 2024 - 2124 Ed, Inc.
**     Copyright 2024 - 2124 Ed
**     All Rights Reserved.
** ###################################################################*/

/**************************************************************************************************/
#ifndef    PRIVATE_LIN_CFG_H
#define    PRIVATE_LIN_CFG_H


#define SYNC_DATA		0x55
#define LIN_IS_MASTER				1			// 是否主节点
#define LIN_BAUDRATE				19200		// LIN波特率

#define LIN_DIAG_REQ_ID				0x3C		// LIN诊断请求ID
#define LIN_DIAG_RESP_ID			0x3D		// LIN诊断响应ID

#define LIN_SCHEDULE_PREIODIC		10			// 单位mS


// 帧 ID : 
#define   BackSPCUControl  0x01
#define   SeatSPCUStatus  0x02
#define   SeatSPCUStatus2  0x03

#define   BackSPCUControlFrameLen  8
#define   SeatSPCUStatusFrameLen  8
#define   SeatSPCUStatus2FrameLen  8

// 网络层/传输层向数据链路层请求分段消息时启动N_As计时器，
// 当接收到数据链路层发送完成时，停止N_As计时器。
#define N_As_Max_mS			500//30

// 网络层/传输层接收到帧头(PID)时启动N_Ar计时器，
// 当接收到数据链路层接收到一帧数据时，停止N_As计时器。
#define N_Ar_Max_mS			500//20

// 发送方发送连续帧的间隔时间
#define N_Cs_Max_mS			10

// 接收方接收连续帧的等待时间
#define N_Cr_Max_mS			500//100

// 从节点接收到最后一帧诊断请求之后，需要响应提供数据的时间
#define S_P2_Min_mS 		500//50

// 从节点在丢弃响应数据之前必须接收到从响应帧0x3D 表头的时间
#define S_P2_Max_mS	 		1500//500

// 从节点发送NRC 0x78 之后LIN 从节点能够为提供响应数据所需的时间
#define S_P2_NRC_Max_mS		2000
/**********************************
*帧名称 : BackSPCUControl
*帧  ID : 0x30
*发布者 : BackSPCU
*帧长度 : 1
**********************************/
typedef union
{
    uint8_t data[BackSPCUControlFrameLen];
    struct
    {
        uint8_t SecRowRiSeatMassgModCmd : 4;
        uint8_t LvPwrSysErr : 2;
        uint8_t UnusedBits_0_6_7 : 2;
        uint8_t SecRowRiSeatMassgLvlCmd : 3;
        uint8_t SecRowRiSeaFlankAdjSwt : 3;
        uint8_t UnusedBits_1_6_7 : 2;
        uint8_t SecRowRiSeatMassgSwt : 1;
        uint8_t SecRowRiSeatFlankAdjmtCmd : 3;
        uint8_t RRSeatSupportPosnCmd : 3;
        uint8_t UnusedBits_2_7_7 : 1;
        uint8_t SysPowerMod : 2;
        uint8_t TranPMode_Sts : 1;
        uint8_t Dyn_PwrSv_Lvl : 3;
        uint8_t LowPowerEgyMngmntModReq : 2;
        uint8_t UnusedBits_4_0_7 : 8;
        uint8_t UnusedBits_5_0_7 : 8;
        uint8_t UnusedBits_6_0_7 : 8;
        uint8_t UnusedBits_7_0_7 : 8;
    }Bit;
}BackSPCUControlType;


/**********************************
*帧名称 : SeatSPCUStatus
*帧  ID : 0x33
*发布者 : Seat SPCU
*帧长度 : 8
**********************************/
typedef union
{
    uint8_t data[SeatSPCUStatusFrameLen];
    struct
    {
        uint8_t SMSM_SR_RespErr : 1;
        uint8_t RRSeatMassgLvlSetSts : 3;
        uint8_t RRSeatMassgModSts : 4;
        uint8_t RRSeatSupportPosnSts : 3;
        uint8_t SMSM_SR_SysVoltSts : 2;
        uint8_t SecRowRiSeatMassgIntfDispBtn : 1;
        uint8_t UnusedBits_1_6_7 : 2;
        uint8_t UnusedBits_2_0_7 : 8;
        uint8_t UnusedBits_3_0_7 : 8;
        uint8_t UnusedBits_4_0_7 : 8;
        uint8_t UnusedBits_5_0_7 : 8;
        uint8_t UnusedBits_6_0_7 : 8;
        uint8_t UnusedBits_7_0_7 : 8;
    }Bit;
}SeatSPCUStatusType;

/**********************************
*帧名称 : SeatSPCUStatus2
*帧  ID : 0x36
*发布者 : Motor1
*帧长度 : 8
**********************************/
typedef union
{
    uint8_t data[SeatSPCUStatus2FrameLen];
    struct
    {
        uint8_t PumpStatus : 8;
        uint8_t UnusedBits_1_0_7 : 8;
        uint8_t UnusedBits_2_0_7 : 8;
        uint8_t UnusedBits_3_0_7 : 8;
        uint8_t UnusedBits_4_0_7 : 8;
        uint8_t UnusedBits_5_0_7 : 8;
		uint8_t UnusedBits_6_0_7 : 8;
        uint8_t UnusedBits_7_0_7 : 8;
    }Bit;
}SeatSPCUStatus2Type;

// 指示类型
typedef enum
{
	LIN_IND_TYPE_STATUS = 0,		// 指示状态信息
	LIN_IND_TYPE_TRAN,				// 指示数据传输

}LIN_IND_TYPE;


typedef enum
{
	LIN_TRAN_DIR_RECV,				// 接收
	LIN_TRAN_DIR_SEND,				// 发送

}LIN_TRAN_DIR;


// LIN消息路由
typedef enum
{
	LIN_MSG_ROUTE_DIAG = 0,			// 将数据路由至诊断
	LIN_MSG_ROUTE_NORMAL,			// 将数据路由至默认通信

}LIN_MSG_ROUTE;

typedef enum
{
	LIN_CHKSUM_TYPE_CLASSIC = 0,	// 经典校验
	LIN_CHKSUM_TYPE_ENHANCE,		// 增强校验
}LIN_CHKSUM_TYPE;


// LIN消息定义
typedef struct
{
	uint8_t id;						// ID
	uint8_t Len;						// 数据长度
	uint8_t *pdata;
	LIN_TRAN_DIR 	TransfDir;		// 传输方向
	uint8_t delay_integer;

}LIN_MSG_TYPE;
extern BackSPCUControlType BackSPCUControl_Msg;
extern SeatSPCUStatusType SeatSPCUStatus_Msg;
extern SeatSPCUStatus2Type SeatSPCUStatus2_Msg;
extern const LIN_MSG_TYPE  LIN_Msg_Tbl[];
extern uint8_t LIN_Msg_Tbl_Get_Item_Amount(void);
extern void LIN_Msg_Tbl_Init(void);	

#endif    /* PRIVATE_LIN_CFG_H_ */
