/**************************************************************************************************/

/*  ###################################################################
**     This component module is generated by Lin_Geny. Do not modify it.
**
**     @file      lin_cfg.c
**
**     @date      2025-01-09 15:41:07 PM
**
**     @brief     Lin configuration file
**
**     @version   1.00.05
**
**     @Toolversion   LIN Geny V1.10
**
**     @Ldf1FileName   MX11_LZCU_LIN5_240528.ldf
**
**     @Ldf2FileName
**
**     @Ldf3FileName
**
**     @Ldf4FileName   
**
**     Copyright : 2024 - 2124 Ed, Inc.
**     Copyright 2024 - 2124 Ed
**     All Rights Reserved.
** ###################################################################*/

/**************************************************************************************************/
#include "Include.h"
uint8_t LIN_Msg_Tbl_Amount = 0;	// 保存表中id的数量

BackSPCUControlType BackSPCUControl_Msg;
SeatSPCUStatusType SeatSPCUStatus_Msg;
SeatSPCUStatus2Type SeatSPCUStatus2_Msg;


const LIN_MSG_TYPE  LIN_Msg_Tbl[] =
{
	{BackSPCUControl, BackSPCUControlFrameLen, BackSPCUControl_Msg.data, LIN_TRAN_DIR_SEND, 5},
	{SeatSPCUStatus,  SeatSPCUStatusFrameLen,  SeatSPCUStatus_Msg.data,  LIN_TRAN_DIR_RECV, 5},	//
	{SeatSPCUStatus2, SeatSPCUStatus2FrameLen, SeatSPCUStatus2_Msg.data, LIN_TRAN_DIR_RECV, 5},	//

};


/*******************************************************************************
*函数名      	：LIN_Msg_Tbl_Init
*函数功能  	：计算表中的id数量
*函数参数    	：无
*函数返回值	：无
*说明		：无
*******************************************************************************/
void LIN_Msg_Tbl_Init(void)
{
	LIN_Msg_Tbl_Amount = sizeof(LIN_Msg_Tbl)/sizeof(LIN_Msg_Tbl[0]);
}

/*******************************************************************************
*函数名      	：LIN_Msg_Tbl_Get_Item_Amount
*函数功能  	：获取算表中的id数量
*函数参数    	：无
*函数返回值	：id数量
*说明		：无
*******************************************************************************/
uint8_t LIN_Msg_Tbl_Get_Item_Amount(void)
{
	return LIN_Msg_Tbl_Amount;
}


