/**************************************************************************************************/

/*  ###################################################################
**     This component module is generated by Lin_Geny. Do not modify it.
**
**     @file      lin_cfg.c
**
**     @date      2025-10-21 14:41:51 PM
**
**     @brief     Lin configuration file
**
**     @version   1.00.06
**
**     @Toolversion   LIN Geny V1.16
**
**     @Ldf1FileName   MX11_LZCU_LIN5_240528.ldf
**
**     @Ldf2FileName   
**
**     @Ldf3FileName   
**
**     @Ldf4FileName   
**
**     Copyright : 2024 - 2124 Ed, Inc.
**     Copyright 2024 - 2124 Ed
**     All Rights Reserved.
** ###################################################################*/

/**************************************************************************************************/
#include "Include.h"

const l_ifc_handle g_lin_hardware_ifc[HARDWARE_INSTANCE_COUNT] = {LI0};
const uint32_t g_lin_virtual_ifc[LIN_NUM_OF_IFCS] = {0};
/* definition and initialization of signal array */
volatile uint8_t    g_lin_Diag_Tx_data_Len =0;
volatile uint8_t    g_lin_Diag_Tx_data_buffer[LIN_DIAG_TX_BUF_SIZE] ={0xFF};
volatile uint8_t    g_lin_Diag_Rx_data_buffer[LIN_DIAG_RX_BUF_SIZE] ={0xFF};

volatile uint8_t    g_lin_Proprietary_Tx_data_buffer[LIN_PROPRIETARY_TX_BUF_SIZE] ={0xFF};
volatile uint8_t    g_lin_Proprietary_Rx_data_buffer[LIN_PROPRIETARY_RX_BUF_SIZE] ={0xFF};
lin_user_config_t lin1_InitConfig0 = {
    .baudRate = 19200U,
    .nodeFunction = (bool)SLAVE,
    .autobaudEnable = false,
    .classicPID = NULL,
    .numOfClassicPID = 0U,
};
volatile uint8_t    g_lin_tbl_use_index = LI0_Schedule_Index0;
/* definition and initialization of signal array */
volatile uint8_t    g_lin_frame_tbl0_data_buffer[LIN_FRAME_TBL0_BUF_SIZE] =
{
/* start of frame  Reseverd */
   0x00 /* 0 */
  ,0x00 /* 1 */
  ,0x00 /* 2 */
  ,0x00 /* 3 */
  ,0x00 /* 4 */
  ,0x00 /* 5 */
  ,0x00 /* 6 */
  ,0x00 /* 7 */

};
/* ********************************  Frame table **********************************/
static const lin_frame_t lin_frame_tbl0[LIN_TBL0_NUM_OF_FRMS] ={

	{ LIN_FRM_DIAG, 8, LIN_RES_SUB, 0}

   ,{ LIN_FRM_DIAG, 8, LIN_RES_PUB, 0  }

   ,{ LIN_FRM_PROPRIETARY, 8, LIN_RES_SUB, 0  }

   ,{ LIN_FRM_PROPRIETARY, 8, LIN_RES_PUB, 0  }

};
static uint8_t LI0_lin_Schedule_TblEnable[LIN_NUM_OF_SCHEDULE_TBL] ={TRUE};
static uint8_t LI0_lin_tbl0_NodeSendRecvEnable[LIN_TBL0_NUM_OF_FRMS] ={TRUE,TRUE,TRUE,TRUE};

static uint8_t LI0_lin_tbl0_configuration_RAM[LI0_LIN_TBL0_SIZE_OF_CFG]= {0x00, 0x3C, 0x3D, 0x3E, 0x3F, 0xFF};

static const uint16_t  LI0_lin_tbl0_configuration_ROM[LI0_LIN_TBL0_SIZE_OF_CFG]= {0x0000,  0x3C, 0x3D, 0x3E, 0x3F, 0xFFFF};

lin_protocol_ResponeErr_Type LI0_lin_ResponeErr_Status;
/* ************** Node attributes Initialization  ****************************/
const lin_node_attribute_t      g_lin_node_attribute_array[LIN_NUM_OF_SLAVE_IFCS]= {
    /*  LI0 **/
    {
        .product_id = {0x0000, 0x0000, 0x00},   /*{<supplier_id>,<function_id>,<variant>}*/
        .ResponeErr_Type = &LI0_lin_ResponeErr_Status,

    }
};

/* **************************LIN interface configuration ****************************/
const lin_protocol_user_config_t g_lin_protocol_user_cfg_array[LIN_NUM_OF_IFCS] = {

    /* Interface_name = LI0 */
    {
        .protocol_version = LIN_PROTOCOL_21,         /*lin_protocol_version */
        .language_version = LIN_PROTOCOL_21,         /*lin_language_version */
        .diagnostic_class = LIN_DIAGNOSTIC_CLASS_I,            /* LIN Diagnostic Class */
        .function = (bool)LIN_SLAVE,                  /*  function LIN_SLAVE*/

        .number_of_schedule_Tbl = LIN_NUM_OF_SCHEDULE_TBL,                            /*  num_of_Schedule tbl */
        .frame_start = 0,                              /*  frame_start */
        .max_idle_timeout_cnt =  8461,     /* Max Idle Timeout Count ,Max Time 5s*/
        .slave_ifc_handle = LI0_Slave,
        .lin_user_config_ptr = &lin1_InitConfig0,
        .list_schedule_tbl_En_ptr = LI0_lin_Schedule_TblEnable,        /* Schedule Tbl Enable*/

    }
};
/* **************************LIN LDF Infomation configuration ****************************/
const lin_protocol_Ldf_config_t g_lin_protocol_ldf_cfg_array[LIN_NUM_OF_SCHEDULE_TBL] = {

{
        .number_of_configurable_frames = LIN_TBL0_NUM_OF_FRMS,          /*  num_of_frames */
        .number_of_configurable_buf = LIN_FRAME_TBL0_BUF_SIZE,          /*  num_of_frames buf*/
        .list_Node_tbl_En_ptr = LI0_lin_tbl0_NodeSendRecvEnable,        /* frame SendRecv Enable*/
        .frame_tbl_ptr = lin_frame_tbl0,                                 /*  frame_tbl */
        .list_identifiers_ROM_ptr = LI0_lin_tbl0_configuration_ROM,                  /*  *configuration_ROM */

        .list_identifiers_RAM_ptr = LI0_lin_tbl0_configuration_RAM,                            /*  *configuration_RAM */
        .Frame_Buff_data_ptr = g_lin_frame_tbl0_data_buffer,                              /*  *frame cfg buff ptr*/

    },
};
void ld_Set_lin_schedule_tbl_use_En(uint8_t OpScheduleTblIndex,uint8_t data)
{
    if(OpScheduleTblIndex<(g_lin_protocol_user_cfg_array[LI0].number_of_schedule_Tbl))
    {
        g_lin_protocol_user_cfg_array[LI0].list_schedule_tbl_En_ptr[OpScheduleTblIndex] = data;
    }

}

lin_protocol_ResponeErr_Type* ld_Get_lin_ResponeErr_Status(void)
{
    return &LI0_lin_ResponeErr_Status; 
}
void ld_Set_id_Respone_En(uint8_t OpScheduleTblIndex,uint8_t OpFrameIndex,uint8_t data)
{
    if(OpFrameIndex<(g_lin_protocol_ldf_cfg_array[OpScheduleTblIndex].number_of_configurable_frames))
    {
        g_lin_protocol_ldf_cfg_array[OpScheduleTblIndex].list_Node_tbl_En_ptr[OpFrameIndex] = data;
    }

}
