/**************************************************************************************************/

/*  ###################################################################
**     This component module is generated by Lin_Geny. Do not modify it.
**
**     @file      lin_cfg.h
**
**     @date      2025-10-21 14:41:51 PM
**
**     @brief     Lin configuration file
**
**     @version   1.00.06
**
**     @Toolversion   LIN Geny V1.16
**
**     @Ldf1FileName   MX11_LZCU_LIN5_240528.ldf
**
**     @Ldf2FileName   
**
**     @Ldf3FileName   
**
**     @Ldf4FileName   
**
**     Copyright : 2024 - 2124 Ed, Inc.
**     Copyright 2024 - 2124 Ed
**     All Rights Reserved.
** ###################################################################*/

/**************************************************************************************************/
#ifndef    LIN_CFG_H
#define    LIN_CFG_H


/* Implements    : SUPPORT_MASTER_MODE_Class */
#define SUPPORT_MASTER_MODE     0U /* Equal to 1 when have at least one master interface */
/* Implements    : SUPPORT_SLAVE_MODE_Class */
#define SUPPORT_SLAVE_MODE      1U  /* Equal to 1 when have at least one slave interface */

/* Implements    : SUPPORT_PROTOCOL_21_Class */
#define SUPPORT_PROTOCOL_21     1U /* Equal to 1 when have at least one LIN2.1 or LIN2.2 interface */
/* Implements    : SUPPORT_PROTOCOL_J2602_Class */
#define SUPPORT_PROTOCOL_J2602  0U /* Equal to 1 when have at least one J2602 interface */
/* Implements    : SUPPORT_DIAG_CLASS_III_Class */
#define SUPPORT_DIAG_CLASS_III  0U /* Equal to 1 when have at least one ifc with diagnostic class III */
/* Implements    : SUPPORT_DIAG_CLASS_II_Class */
#define SUPPORT_DIAG_CLASS_II   0U /* Equal to 1 when have at least one ifc with diagnostic class II or III */
/* Implements    : SUPPORT_TRANSPORT_LAYER_Class */
#define SUPPORT_TRANSPORT_LAYER 0U /* Equal to 1 to use transport layer */
/* Implements    : SUPPORT_DIAG_SERVICE_Class */
#define SUPPORT_DIAG_SERVICE    1U /* Equal to 1 to use diagnostic service layer */
#define TIME_OUT_UNIT_US 534U

#define HARDWARE_INSTANCE_COUNT    1U
#define LIN_NUM_OF_IFCS  1U
#define LIN_NUM_OF_SLAVE_IFCS 1U
#define LIN_NUM_OF_MASTER_IFCS 0U

#define LIN_DIAG_TX_BUF_SIZE          8U
#define LIN_DIAG_RX_BUF_SIZE          8U

#define LIN_PROPRIETARY_TX_BUF_SIZE          8U
#define LIN_PROPRIETARY_RX_BUF_SIZE          8U
/* ********************************************************************/
/* *************               Interfaces           *******************/
/* ********************************************************************/
typedef enum {
   LI0 = 0x00U,
   INVALID_IFC = 0xFFU
}l_ifc_handle;

typedef enum {
   LI0_Slave = 0x00U,
   INVALID_SLAVE_INDEX = 0xFFU
}l_ifc_slave_handle;
typedef enum {
   INVALID_MASTER_INDEX = 0xFFU
}l_ifc_master_handle;

/* Number of Ldf schedule */
#define LIN_NUM_OF_SCHEDULE_TBL  1U

typedef enum {
    LI0_Schedule_Index0 = 0U
}l_ifc_Schedule_Index;
/* ********************************************************************/
/* *************               Signals              *******************/
/* ********************************************************************/
/* Number of signals */
#define LI0_LIN_TBL0_NUM_OF_SIGS  1U
/* List of signals */
typedef enum {
   /* All signals for LIN Schedule Table0 node */
    
       /* Interface_name = LI0 */
       
     LI0_TBL0_Reseverd_Signal
 

} l_signal_handle_Tbl0;
/**********************************************************************/
/*****************               Frame             ********************/
/**********************************************************************/
/* Number of frames */
#define LIN_TBL0_NUM_OF_FRMS  4U
#define LI0_LIN_TBL0_SIZE_OF_CFG  15U
/* frame buffer size */
#define LIN_FRAME_TBL0_BUF_SIZE          8U
/* List of frames */
typedef enum {
   /* All frames for LIN Schedule Table0 node */
    
   /* Interface_name = LI0 */
     LI0_TBL0_DiagMasterReq
   , LI0_TBL0_DiagSlaveResp
   , LI0_TBL0_PrietaryMasterReq
   , LI0_TBL0_PrietarySlaveResp

} l_frame_handle_Tbl0;
/* ********************************************************************/
/* *************             Configuration          *******************/
/* ********************************************************************/


/* Size of configuration in ROM and RAM used for interface: LI0 */

/* *******************************************************************
 * global macros
 *********************************************************************/
/*FUNCTION**********************************************************************
 *
 * Function Name : BOOL_rd
 * Description   : This function return value of bool signal
 *
 * Implements    : BOOL_rd_Class
 *END**************************************************************************/
#define BOOL_rd(SIGNAL) BOOL_rd_##SIGNAL()

/*FUNCTION**********************************************************************
 *
 * Function Name : BOOL_wr
 * Description   : This function write value A to bool signal
 *
 * Implements    : BOOL_wr_Class
 *END**************************************************************************/
#define BOOL_wr(SIGNAL, A) BOOL_wr_##SIGNAL(A)

/*FUNCTION**********************************************************************
 *
 * Function Name : uint8_t_rd
 * Description   : This function read data from (1-8 bit)signal
 *
 * Implements    : uint8_t_rd_Class
 *END**************************************************************************/
#define uint8_t_rd(SIGNAL) uint8_t_rd_##SIGNAL()

/*FUNCTION**********************************************************************
 *
 * Function Name : uint8_t_wr
 * Description   : This this function write data to (1-8 bit)signal
 *
 * Implements    : uint8_t_wr_Class
 *END**************************************************************************/
#define uint8_t_wr(SIGNAL, A) uint8_t_wr_##SIGNAL(A)

/*FUNCTION**********************************************************************
 *
 * Function Name : uint16_t_rd
 * Description   : This function read data from (8-16 bit)signal
 *
 * Implements    : uint16_t_rd_Class
 *END**************************************************************************/
#define uint16_t_rd(SIGNAL) uint16_t_rd_##SIGNAL()

/*FUNCTION**********************************************************************
 *
 * Function Name : uint16_t_wr
 * Description   : This function write data to (8-16 bit) signal
 *
 * Implements    : uint16_t_wr_Class
 *END**************************************************************************/
#define uint16_t_wr(SIGNAL, A) uint16_t_wr_##SIGNAL(A)

/*FUNCTION**********************************************************************
 *
 * Function Name : l_bytes_rd
 * Description   : This function read data from bytes signal
 *
 * Implements    : l_bytes_rd_Class
 *END**************************************************************************/
#define l_bytes_rd(SIGNAL, start, count, data)  l_bytes_rd_##SIGNAL(start, count, data)

/*FUNCTION**********************************************************************
 *
 * Function Name : l_bytes_wr
 * Description   : This function write data to bytes signal
 *
 * Implements    : l_bytes_wr_Class
 *END**************************************************************************/
#define l_bytes_wr(SIGNAL, start, count, data) l_bytes_wr_##SIGNAL(start, count, data)

/*FUNCTION**********************************************************************
 *
 * Function Name : l_flg_tst
 * Description   : This function return value of flag which related with signal
 *
 * Implements    : l_flg_tst_Class
 *END**************************************************************************/
#define l_flg_tst(FLAG) l_flg_tst_##FLAG()

/*FUNCTION**********************************************************************
 *
 * Function Name : l_flg_clr
 * Description   : This function clear flag which related with signal
 *
 * Implements    : l_flg_clr_Class
 *END**************************************************************************/
#define l_flg_clr(FLAG) l_flg_clr_##FLAG()

#define LIN_TEST_BIT(A,B) ((BOOL)((((A) & (1U << (B))) != 0U) ? 1U : 0U))
#define LIN_SET_BIT(A,B)                      ((A) |= (uint8_t) (1U << (B)))
#define LIN_CLEAR_BIT(A,B)               ((A) &= ((uint8_t) (~(1U << (B)))))
#define LIN_BYTE_MASK  ((uint16_t)(((uint16_t)((uint16_t)1 << CHAR_BIT)) - (uint16_t)1))


/* Returns the low byte of the 32-bit value    */
#define BYTE_0(n)                              ((uint8_t)((n) & (uint8_t)0xFF))
/* Returns the second byte of the 32-bit value */
#define BYTE_1(n)                        ((uint8_t)(BYTE_0((n) >> (uint8_t)8)))
/* Returns the third byte of the 32-bit value  */
#define BYTE_2(n)                       ((uint8_t)(BYTE_0((n) >> (uint8_t)16)))
/* Returns high byte of the 32-bit value       */
#define BYTE_3(n)                       ((uint8_t)(BYTE_0((n) >> (uint8_t)24)))

/* INTERFACE MANAGEMENT */

/*FUNCTION**********************************************************************
 *
 * Function Name : l_ifc_init_interface
 * Description   : This static function call to dynamic function l_ifc_init()
 *
 * Implements    : l_ifc_init_interface_Class
 *END**************************************************************************/

#define l_ifc_init_LI0() l_ifc_init(LI0)

#define l_ifc_get_state_LI0() l_ifc_get_state(LI0)
#define l_ifc_Nm_Sleep_State_get    ((LIN_NODE_STATE_SLEEP_MODE == l_ifc_get_state(LI0))?1:0)



#define l_ifc_ld_init_LI0() ld_init(LI0)


#define l_ifc_tl_InstallCallback_Diag_Tx_Data_assignment_LI0(Func)  ld_InstallCallback(Commontl_proto_Callback_Diag_Tx_Data_assignment,Func)
#define l_ifc_tl_InstallCallback_Diag_Tx_Complete_LI0(Func)           ld_InstallCallback(Commontl_proto_Callback_Diag_Tx_Complete,Func)
#define l_ifc_tl_InstallCallback_Diag_Rx_Complete_LI0(Func)           ld_InstallCallback(Commontl_proto_Callback_Diag_Rx_Complete,Func)

#define l_ifc_tl_InstallCallback_Proprietary_Tx_Data_assignment_LI0(Func)  ld_InstallCallback(Commontl_proto_Callback_Proprietary_Tx_Data_assignment,Func)
#define l_ifc_tl_InstallCallback_Proprietary_Tx_Complete_LI0(Func)           ld_InstallCallback(Commontl_proto_Callback_Proprietary_Tx_Complete,Func)
#define l_ifc_tl_InstallCallback_Proprietary_Rx_Complete_LI0(Func)           ld_InstallCallback(Commontl_proto_Callback_Proprietary_Rx_Complete,Func)

#define l_ifc_tl_InstallCallback_App_Tx_Data_assignment_LI0(Func)  ld_ApplyIdInstallCallback(Commontl_proto_Callback_App_Tx_Data_assignment,Func)
#define l_ifc_tl_InstallCallback_App_Tx_Complete_LI0(Func)           ld_ApplyIdInstallCallback(Commontl_proto_Callback_App_Tx_Complete,Func)
#define l_ifc_tl_InstallCallback_App_Rx_Complete_LI0(Func)           ld_ApplyIdInstallCallback(Commontl_proto_Callback_App_Rx_Complete,Func)

/*FUNCTION**********************************************************************
 *
 * Function Name : l_ifc_wake_up_interface
 * Description   : This static function call to dynamic function l_ifc_wake_up()
 *
 * Implements    : l_ifc_wake_up_interface_Class
 *END**************************************************************************/

#define l_ifc_wake_up_LI0() l_ifc_wake_up(LI0)


/*FUNCTION**********************************************************************
 *
 * Function Name : l_ifc_read_status_interface
 * Description   : This static function call to dynamic function l_ifc_read_status()
 *
 * Implements    : l_ifc_read_status_interface_Class
 *END**************************************************************************/

#define l_ifc_read_status_LI0() l_ifc_read_status(LI0)

#define l_lld_timeout_service_LI0()  lin_lld_timeout_service(LI0)
/*FUNCTION**********************************************************************
 *
 * Function Name : l_lld_Id_Respone_Set_LI0
 * Description   : This function Enable which Node ID needs to be sent and received
 *
 * Implements    : ld_Set_id_Respone_En
 *END**************************************************************************/
extern void ld_Set_id_Respone_En(uint8_t OpScheduleTblIndex,uint8_t OpFrameIndex,uint8_t data);
#define l_lld_Id_Respone_Set_LI0(TblIndex,Frameindex,data)  ld_Set_id_Respone_En(TblIndex,Frameindex,data)
/*FUNCTION**********************************************************************
 *
 * Function Name : l_lld_Id_Stbl_use_index_Set_LI0
 * Description   : This function set which LIN schedule table is currently in use
 *
 * Implements    : ld_Set_lin_schedule_tbl_use_index
 *END**************************************************************************/
extern void ld_Set_lin_schedule_tbl_use_En(uint8_t OpScheduleTblIndex,uint8_t data);

#define l_lld_Id_Stbl_use_index_Set_LI0(TblIndex,data)  ld_Set_lin_schedule_tbl_use_En(TblIndex,data)
/*FUNCTION**********************************************************************
 *
 * Function Name : l_lld_Id_lin_ResponeErr_Status_Get_LI0
 * Description   : This function get the current LIN bus error status
 *
 * Implements    : ld_Get_lin_ResponeErr_Status
 *END**************************************************************************/

#define l_lld_Id_lin_ResponeErr_Status_Get_LI0()  ld_Get_lin_ResponeErr_Status()

#endif    /* _LIN_CFG_H_ */
